Makefile, README.md, docker-compose.yml, edxapp/Dockerfile, edxapp/docker-entrypoint.sh, edxapp/wait-for-greenlight.sh
This allows the user to run their own devstack inside the containers.
Yay!
Also, we handle file permissions cleanly: in `docker-entrypoint.sh` we chmod the data and edx-platform files to the same UID of the user on the host machine. No more permission headaches!
@natea  @sampaccoud can you give it a try? I think it's pretty neat ;)
=> Working devstack

.travis.yml
Assets collection is too time-consuming. The Travis build fails after 50
minutes. So we don't test it.
=> Attempt to accelerate travis build

README.md
`$USERNAME` is a special variable in `zsh` and so when we try to set the staff's username to it, it gets the wrong thing. Using STAFFUSERNAME negates this issue. While the command clearly uses `/bin/bash` for the shell, this is getting interpolated prior to hitting that shell (on my machine anyways).
I understand that you may not want to support ZSH so feel free to close this if desired.
=> Fixes #62: Use non-overlapping username variable

tutor/templates/apps/openedx/settings/cms/development.py, tutor/templates/apps/openedx/settings/cms/production.py, tutor/templates/apps/openedx/settings/lms/development.py, tutor/templates/apps/openedx/settings/lms/production.py
This is to improve in situations where we need to override default production/development settings.
Signed-off-by: tonytan4ever <tonytan198211@gmail.com>
=> Improve import in openedx config settings

docs/configuration.rst
As mention in https://github.com/regisb/tutor/issues/192, command `$(tutor config printroot)` have little problem on Mac. And there are other place in the document use `$(tutor config printroot)`, which i don't have chance to try it yet. I will open another PR if encounter this problem again.
=> Add quotes for command `$(tutor config printroot)`

tutor/templates/build/notes/Dockerfile, tutor/templates/build/openedx/Dockerfile, tutor/templates/build/openedx/gunicorn_conf.py, tutor/templates/build/xqueue/Dockerfile
Tutor currently runs a single worker `gunicorn` process.
This PR makes the number of workers dependent on the number of cores: `(2 x $num_cores) + 1`, as recommended in the [gunicorn documentation](http://docs.gunicorn.org/en/stable/design.html#how-many-workers).
=> Tell openedx gunicorn to fork workers based on CPU count

tutor/k8s.py, tutor/local.py, tutor/templates/build/openedx/bin/docker-entrypoint.sh, tutor/templates/local/docker-compose.yml
Tutor is not using any bash-specific feature.
This PR changes (almost) all invocations to /bin/bash replacing them with
`/bin/sh`. It allows building a docker image that does not bundle bash in it.
The file `k8s.py` still has a bash invocation, to make sure this change does not
impact functionality for any user.
=> Do not require bash to be installed in docker containers.

plugins/minio/MANIFEST.in
After I `pip install minio`  and run
```
tutor enable minio
tutor config save
```
minio didn't work.
I thinks is this typo cause setuptool miss the files of patches directory.
=> Fix typo of minio MANIFEST.in

docs/_release_description.md, docs/cli_download.rst
Otherwise it will not be readable by normal users.
=> Fix tutor binary permission error on MacOSX

docs/install.rst, docs/podman.rst
This is a work-in-progress. I'm still testing this, but it looks like it's working as expected, so far.
> https://podman.io/ is meant to be a drop-in replacement for Docker.
> Thus, with some tweaking to the installation environment, it appears
> to be perfectly feasible to run Tutor in a Docker-less environment
> that only has Podman and podman-compose installed.
>
> Add installation instructions for doing just that.
=> doc: Add instructions for running Tutor on Podman

Dockerfile
- Using python:3.7-slim-stretch as base decrease the size of the tutor image from 1.05GB to 282MB.
=> Smaller Dockerfile base image

tutor/templates/build/openedx/bin/reload-gunicorn
Quite a simple change. I found the `reload-gunicorn` bin quite handy, which is broken since the migration to juniper.
=> reload-gunicorn: look for python3 binary

tutor/templates/k8s/deployments.yml
Hello,
This fix avoid that a CMS Worker can read a message for a LMS Worker and vice versa for k8s templates.
Best Regards,
=> k8s workers queues fix

tutor/env.py
Right now if I add .woff or .woff2 fonts files to an Indigo-based theme's `lms/static/fonts` directory, I get the following error:
```
$ /indigo-folder# make
tutor config render --extra-config ./config-totem.yml ./theme "$(tutor config printroot)/env/build/openedx/themes/indigo-totem"
Error loading template lms/static/fonts/NotoSans-Bold.woff
File "/home/maarten/.local/bin/tutor", line 8, in <module>
sys.exit(main())
File "/home/maarten/.local/lib/python3.8/site-packages/tutor/commands/cli.py", line 38, in main
cli()  # pylint: disable=no-value-for-parameter
File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
rv = …
```
=> Support .woff and .woff2 file format for fonts

CHANGELOG.md, tutor/templates/apps/nginx/cms.conf, tutor/templates/apps/nginx/lms.conf
As proposed in https://discuss.overhang.io/t/editing-nginx-lms-and-cms-conf/1096
This allows yaml plugins to define a `nginx-lms` and `nginx-cms` block. The block gets inserted in the lms and cms server configuration for nginx. For example, this plugin proxies requests to `/js-components` to an external website (needs `ca-certificates` bundle installed on the host machine):
```
cat tutor-plugins/totem-proxy.yml 
---
name: totem-proxy
version: 0.1.0
patches:
nginx-lms: |
location /js-components/ {
proxy_ssl_verify on;
proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
proxy_pass https://totem-project.org/js-components/;
proxy_ssl_server_name on;
}
nginx-cms: |
location /js-components/ {
proxy_ssl_verify on;
proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt; …
```
=> Add option to patch lms and cms nginx server block

CHANGELOG.md, tutor/templates/build/openedx/Dockerfile
As discussed in https://discuss.overhang.io/t/lms-worker-timeout-issue/1057/8, the timeout of the gunicorn worker is a bit low, causing the worker to crashloop on slower systems. By increasing the timeout to 120 seconds, the worker should have time to come up before it gets restarted.
=> Increase the timeout of the gunicorn worker command in openedx Dockerfile

docs/dev.rst
When I tried running `openedx-assets build` on my `tutor dev lms` machine, I got an error: 
```
openedx@1dfe0ece7805:~/edx-platform$ openedx-assets build --env=dev
mkdir_p path('common/static/common/js/vendor')
mkdir_p path('common/static/common/css')
mkdir_p path('common/static/common/css/vendor')
Copying vendor files into static directory
File "/openedx/bin/openedx-assets", line 218, in <module>
main()
File "/openedx/bin/openedx-assets", line 89, in main
args.func(args)
File "/openedx/bin/openedx-assets", line 94, in run_build
run_npm(args)
File "/openedx/bin/openedx-assets", line 117, in run_npm
assets.process_npm_assets()
File "/openedx/edx-platform/pavelib/assets.py", line 643, in process_npm_assets
copy_vendor_library(library)
File …
```
=> Advice people to run npm install before running openedx-assets build

CHANGELOG.md, tutor/templates/build/openedx/settings/partials/assets.py, tutor/templates/build/openedx/settings/partials/i18n.py
As discussed here https://discuss.overhang.io/t/proposal-for-addition-of-some-patches/1309, this PR adds two new patches to
set some extra settings used during the collectstatic and i18ncompile processes.
=> Add patches that enable adding settings during build process (collectstatic and i18ncompile).

tutor/templates/apps/caddy/Caddyfile
After upgrading from Juniper to Koa, we have noticed our SAML authentications requests started to fail.
Upon investigation this was caused by the implementation of Caddy. 
Previously, nginx was setting the `X-Forwarded-Port` header upstream to openedx. It was explicitly defined in the configuration file in earlier versions of Tutor.
Caddy will set some headers like `X-Forwarded-For` by default, however it will not set `X-Forwarded-Port` by default.
This PR modifies the Caddyfile to set this header. The current nginx configuration will pass this header through transparently.
Further information about the SAML issue is below.
The OneLogin SAML library will use the incoming host and port information to validate that a client is calling back to the exact ACS URL that was specified in the …
=> Fix SAML 'Invalid Request' Error

CHANGELOG.md, tutor/templates/build/openedx/Dockerfile
All releases of py2neo prior to 4.0.0 were stripped from Pypi, so we
need to install this dependency from source.
See:
https://github.com/openedx/build-test-release-wg/issues/37
https://github.com/edx/edx-platform/pull/27168
Close #411.
=> fix: missing py2neo dependency breaks `images build openedx`

CHANGELOG.md, tests/test_plugins.py, tutor/plugins.py
When the PLUGINS config entry is None (`PLUGINS:`), the following error
was being triggered:
File "/.../tutor/tutor/plugins.py",
line 304, in is_enabled
return name in config.get(CONFIG_KEY, [])
TypeError: argument of type 'NoneType' is not iterable
This is ready for review @BbrSofiane.
=> fix: TypeError when PLUGINS is None

docs/configuration.rst
See: https://discuss.overhang.io/t/translating-login-registration-page/1378/3
This should also address issue #410.
This is ready for review @overhangio/tutor-developers
=> docs: non-ascii locales must specify a content-type

docs/configuration.rst
See: https://discuss.overhang.io/t/managed-rds-mysql-8-0-not-compatible-with-current-docker-compose/1429/3
When running the command `tutor local init` with MySQL >5.7, the script will error as the `IDENTIFIED BY` syntax is not supported for the `GRANT` command anymore in later versions of MySQL.
=> docs: mention MySQL external version

CHANGELOG.md, tutor/templates/build/openedx-dev/Dockerfile, tutor/templates/build/openedx/Dockerfile
As discussed here https://discuss.overhang.io/t/proposal-for-addition-of-some-patches/1309/4?u=eric.herrera, this PR adds patches to openedx Dockerfiles which make more flexible the installation of extra/private python requirements.
=> feat: Openedx Dockerfile enhancements

Makefile, tests/test_config.py, tests/test_env.py, tests/test_images.py, tests/test_plugins.py, tutor/bindmounts.py, tutor/commands/android.py, tutor/commands/compose.py, tutor/commands/config.py, tutor/commands/context.py, tutor/commands/dev.py, tutor/commands/images.py, tutor/commands/k8s.py, tutor/commands/local.py, tutor/commands/webui.py, tutor/config.py, tutor/env.py, tutor/images.py, tutor/interactive.py, tutor/jobs.py, tutor/plugins.py, tutor/serialize.py, tutor/types.py
I stumbled upon a bug that should have been detected by the type checking. Turns out, considering that config is of type Dict[str, Any] means that we can use just any method on all config values -- which is terrible. I discovered this after I set `config["PLUGINS"] = None`: this triggered a crash when I enabled a plugin.
We resolve this by making the Config type more explicit. We also take the opportunity to remove a few cast statements.
Pylint now also checks for unused imports.
I understand this is a complex PR -- well, we are still in the process of figuring out how to best use mypy.
=> refactor: better config type

CHANGELOG.md, tests/test_serialize.py, tutor/serialize.py
This fix allows using a multiple line formatted Yaml string as input for setting a Tutor config value.
=> fix: YamlParamType supports line terminators

CHANGELOG.md, tutor/templates/build/openedx/Dockerfile
502 was observed when default size 4096 being hit
Close #426
This is equivalent to https://github.com/overhangio/tutor-ecommerce/commit/6df2c99362ee12239eb27b79455539411e4d479e
=> Add uwsgi buffer size to prevent its exceeding

CHANGELOG.md, tests/test_bindmounts.py, tutor/bindmounts.py, tutor/commands/compose.py
When running `tutor local quickstart -p` we were getting the following error:
Usage: custom [OPTIONS] ARGS...
Try 'custom --help' for help.
Error: Missing argument 'ARGS...'.
The docker-compose command sometimes accept a single command ("pull") with zero
argument.
See: https://discuss.overhang.io/t/local-quickstart-not-working-when-pullimages-enabled/1526
This is ready for review cc @overhangio/tutor-developers.
=> fix: crash during `local quickstart -p`

CHANGELOG.md, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/docs.txt
All pallets project requirement had a major upgrade today:
https://palletsprojects.com/blog/flask-2-0-released/
We are not yet compatible with click 8.0 and others. In particular,
click-repl imports modules which are no longer available. Until we can
upgrade, we add constraints to the requirements files.
The following error was being raised:
$ tutor plugins list
File "/home/data/regis/tmp/testtutor/bin/tutor", line 5, in <module>
from tutor.commands.cli import main
File "/home/data/regis/tmp/testtutor/lib/python3.6/site-packages/tutor/commands/cli.py", line 6, in <module>
import click_repl
File "/home/data/regis/tmp/testtutor/lib/python3.6/site-packages/click_repl/__init__.py", line 6, in <module>
import click._bashcomplete
ModuleNotFoundError: No module …
=> fix: requirements of pallets project

CHANGELOG.md, tutor/templates/apps/openedx/config/lms.env.json
Discussion email notification relies on edx_ace and celery routing
key for ace is not set properly by default, which causes the send
mail task is never consumed.
=> fix discussion notification not work.

CHANGELOG.md, tutor/templates/apps/openedx/settings/partials/common_all.py
As described in issue #284, tutor does not come with codejail enabled out of
the box. Actually, we don't even have a working plugin, yet. To prevent users
from running unsafe code, we explicitely disable python-evaluated input by
disabling the "python" interpreter. This might break some courses; thus, this
is a non-backward compatible change.
=> security: disable python-evaluated input by default

requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/docs.txt, tests/test_env.py, tutor/env.py
We were forced to pin click to < v8 because of missing dependencies. In
particular, click_repl was broken. This is no longer the case, as click_repl
0.20 was published. Also, Jinja2 now includes type annotations, which allows us
to get rid of a few "# type: ignore" statements.
We take the opportunity to upgrade all requirements, which allows us resolve a
security issue on urllib3<1.26.0.
=> feat: upgrade pinned requirements to click 8+

CHANGELOG.md, tutor/commands/k8s.py
In most cases, it makes very little sense to edit the namespace that an
application is running in. Quite often, users are granted access to just one
namespace and don't have the necessary rights to edit the namespace -- and for
good security reasons. In such cases, the k8s namespace object already exists
and there is no need for the user to edit or create it. Here, what we do is
that we create the namespace only if it does not exist. This should solve quite
a few permission issues, notably for Openshift users.
This is ready for review @overhangio/tutor-developers. cc @menardorama
=> K8s namespace permission improvement

CHANGELOG.md, tutor/templates/apps/nginx/lms.conf
It was reported that existing users could not sign-in after a Koa -> Lilac
upgrade. This is due to the fact that cookies exceed the 4kb limit, which is
rejected by nginx. The fix consists in increasing this limit to 8kb:
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffer_size
This issue was reported here: https://discuss.overhang.io/t/lilac-upgrade-login-issues/1617
Note that I was not able to reproduce the issue. The fix was tested by the
issue reporter.
=> fix: "upstream sent too big header" nginx errors

CHANGELOG.md, tutor/commands/config.py
There are some cases where we want to skip updating `config.yml` and simply want to generate the environment. This PR introduces a new flag `-e` / `--env-only` for `tutor config save` command. Which allows updating/creating the environment without updating `config.yml`.
Related conversation - https://discuss.overhang.io/t/avoid-writing-env-variables-to-config-yml/1665
1. Pull this PR
2. Generate a new config by running `tutor config save`.
3. Set k8s namespace in the environment - `export TUTOR_K8S_NAMESPACE=testnamespace`
4. Run `tutor config save -e` 
5. `K8S_NAMESPACE` will not appear in `config.yml`. Without this PR, `K8S_NAMESPACE` would have been set in the `config.yml` file.
=> Skip updating config.yml

CHANGELOG.md, tests/test_plugins.py, tutor/commands/plugins.py, tutor/plugins.py
When disable a plugin that set config entried, such as the minio plugin, tutor was logging the following:
Disabling plugin minio...
Removed config entry OPENEDX_AWS_ACCESS_KEY=openedx
Removed config entry OPENEDX_AWS_SECRET_ACCESS_KEY={{ MINIO_AWS_SECRET_ACCESS_KEY }}
Plugin disabled
The config values were not rendered during printing, which is a shame, because
the whole point of this log line is to warn users of passwords/secrets that are
being removed. Here, we make sure that the config values are properly rendered.
The new logs are now:
Disabling plugin minio...
Removing config entry OPENEDX_AWS_ACCESS_KEY=openedx
Removing config entry OPENEDX_AWS_SECRET_ACCESS_KEY=64vpCVLxhDxBuNjakSrX4CQg
Plugin disabled
=> fix: better logging during `plugins disable`

docs/local.rst
nginx/openedx.conf was a configuration file provided to configure
proxies on the host. This file no longer ships with Tutor since v11.0.0.
See: https://discuss.overhang.io/t/local-deployment-webproxy/1688
=> fix: don't refer to obsolete proxy config in docs

docs/install.rst, docs/plugins/api.rst
Instructions actually changed after the upgrade to Click 0.8.
See:
https://click.palletsprojects.com/en/8.0.x/changes/?highlight=completion#version-8-0-0
https://click.palletsprojects.com/en/8.0.x/shell-completion/
Close #457.
=> fix: docs instructions to enable shell completion

CHANGELOG.md, tutor/commands/k8s.py, tutor/templates/k8s/jobs.yml, tutor/templates/local/docker-compose.jobs.yml
An issue with the latest release of docker-compose was reported here:
https://discuss.overhang.io/t/undefined-entrypoint-throws-error-in-docker-compose-2-0-0-beta-4/1716
The mysql-job definition had an empty entrypoint (`[]`). This was causing the following error:
the initiation of mysql fails with “services.mysql-job.entrypoint must be a string …
Error: Command failed with status 15”
I can't remember at all why we had to define an empty entrypoint. It probably
has to do with the fact that we could not run `sh -e -c "..."` commands in
mysql jobs. Similarly, the k8s job definition sets `command: []`. I tested both
local and k8s deployments without these definitions and they work just fine. So
I guess we can get rid of them.
=> fix: empty entrypoints in docker-compose=2.0.0.beta4

CHANGELOG.md, tutor/commands/k8s.py
This reverts commit 6f04223d0135e1debb005f2a9802f081ed21d203.
It turns out that we cannot ignore "command: []" statements in k8s manifests.
That's because there is no way to clear entrypoint in k8s manifests, but
sometimes we do need to bypass the entrypoints. For instance, the minio client
container sets "mc" as the default entrypoint, which does not work with our job
logic.
As a consequence, Tutor becomes incompatible with docker-compose 2.0.0.beta4.
The "entrypoint must be a string" error is actually an upstream bug:
https://github.com/docker/compose-cli/issues/1848
See:
- The corresponding minio issue: https://github.com/overhangio/tutor-minio/issues/9
- The previous conversation about empty entrypoints: https://discuss.overhang.io/t/undefined-entrypoint-throws-error-in-docker-compose- …
=> Revert "fix: empty entrypoints in docker-compose=2.0.0.beta4"

docs/plugins/examples.rst
My understanding is that `THIRD_PARTY_AUTH_BACKENDS` is a list in lms.env.json that is used to generate the value of Django's `AUTHENTICATION_BACKENDS` setting.
=> Fix third-party auth example

CHANGELOG.md, docs/local.rst, tutor/commands/compose.py, tutor/commands/k8s.py
This feature was previously undocumented.
See: https://discuss.overhang.io/t/override-and-docker-compose/1857
EDIT: in addition, we make it possible to override job-specific configs. To simplify the code, we get rid of the deprecated way of running jobs, which dates back from v3.12.0. See: https://discuss.overhang.io/t/problem-fetching-saml-idp-metadata/1330/23
=> docs: using docker-compose.override.yml

CHANGELOG.md, tutor/templates/build/openedx/Dockerfile
- Replace `git patch` by `git cherry-pick` for a cleaner git tree.
- Add a "openedx-dockerfile-post-git-checkout" patch to enable plugin developers to patch edx-platform.
See the commit descriptions for more information.
=> feat: cleaner git patch

CHANGELOG.md, tutor/templates/apps/openedx/settings/partials/common_lms.py
Previously, the logo included in emails was loaded from edX' CDN. Here, we make
sure that the logo is actually the same as the site logo. Because the logo may
be theme-specific, we need to compute the logo url at runtime, and use a
lazily-evaluated string.
This is for #447.
This is ready for review @overhangio/tutor-developers, and in particular @BbrSofiane.
=> improvement: correctly set email logo

CHANGELOG.md, tests/test_utils.py, tutor/utils.py
On Mac OS M1 (ARM processor), when the GMP library is available, pycryptodome
crashes with a segmentation fault during the generation of the RSA keys.
Upstream issue: https://github.com/Legrandin/pycryptodome/issues/506
Upstream fix: https://github.com/Legrandin/pycryptodome/pull/541
Close #473.
=> fix: segmentation fault on Mac OS M1 (Big Sur)

CHANGELOG.md, docs/dev.rst, tutor/templates/apps/openedx/settings/cms/test.py, tutor/templates/apps/openedx/settings/lms/test.py, tutor/templates/apps/openedx/settings/partials/common_test.py, tutor/templates/build/openedx-dev/Dockerfile, tutor/templates/build/openedx-dev/bin/docker-entrypoint-test.sh
It should be unnecessary to build a custom openedx-dev Docker image. All tests
can run from within the dev Docker image, with a couple additional environment
variables.
=> feat: make it easier to run edx-platform unit tests

CHANGELOG.md, tutor/commands/local.py
When upgrading mongodb, the mongodb container takes a little while to become
ready. Running the "exec" command thus triggers an error:
docker-compose -f /path/to/env/local/docker-compose.yml -f /path/to/env/local/docker-compose.prod.yml --project-name tutor_local exec mongodb mongo --eval db.adminCommand({ setF
eatureCompatibilityVersion: "4.0" })
MongoDB shell version v4.0.24
connecting to: mongodb://127.0.0.1:27017/?gssapiServiceName=mongodb
2021-06-14T10:53:21.510+0000 E QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused:
connect@src/mongo/shell/mongo.js:356:17
@(connect):2:6
exception: connect failed
Error: Command failed with status 1: docker-compose -f …
=> fix: mongodb upgrade during koa -> lilac migration

CHANGELOG.md, tutor/templates/apps/openedx/settings/partials/common_lms.py
See: https://discuss.overhang.io/t/no-activation-email-errors-logged-on-user-sign-up/1969
A 500 error was being triggered during user registration.
File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/openedx/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, …
=> fix: 500 error during user registration

CHANGELOG.md, docs/configuration.rst, tutor/commands/images.py
This PR adds the ability to pass any docker build [options](https://docs.docker.com/engine/reference/commandline/build/) via the newly added `--docker-arg` flag.
https://discuss.overhang.io/t/ability-to-specify-cache-sources-during-image-build/1890
- Pull this PR
- Try to build the `openedx` image with - `tutor images build openedx --docker-arg="--build-arg" --docker-arg="EDX_PLATFORM_VERSION=open-release/koa.3"` command
- You should see arg `EDX_PLATFORM_VERSION` is set to `open-release/koa.3` in the output of docker image build command.
=> [BB-4702] Ability to pass docker build options

CHANGELOG.md, tutor/commands/compose.py
Previously, we were building all images every time we ran a "local start"
command. This was causing unnecessary rebuild. Here, instead, we make use of
the `docker-compose up --build`. This means that only the required images will
be rebuilt.
=> fix: bypass build to accelerate "local start"

CHANGELOG-nightly.md, tutor/templates/k8s/deployments.yml
Caddy should always be running, even when ENABLE_WEB_PROXY is false.
It's the service that should not always be running.
=> fix: always run Caddy on Kubernetes

CHANGELOG.md, tutor/plugins.py
- Do not crash on non-importable plugins.
- Always print plugins sorted by name.
=> A couple minor improvements to plugin management

CHANGELOG.md, tutor/templates/k8s/jobs.yml
When running `tutor k8s` we can disable the forum deployment and service by setting `RUN_FORUM` to `false`, but the corresponding job is added to `jobs.yml` unconditionally.
Add a conditional to `tutor/templates/k8s/jobs.yml` so that the forum job definition is only included when `RUN_FORUM` is `true`.
Fixes #525.
=> Include the forum job only if RUN_FORUM is set

CHANGELOG.md, docs/dev.rst, tutor/templates/dev/docker-compose.yml, tutor/templates/local/docker-compose.jobs.yml, tutor/templates/local/docker-compose.prod.yml, tutor/templates/local/docker-compose.yml
Remove trailing slashes in volume paths for docker-compose v2 compatibility.
@overhangio/tutor-developers this is ready for review.
=> fix: remove trailing slashes in volume paths for docker-compose v2 compatibility

CHANGELOG-nightly.md, tutor/templates/kustomization.yml
Through the `commonLabels` directive in `kustomization.yml`, all resources get a label named "app.kubernetes.io/version", which is being set to the Tutor version at the time of initial deployment.
When the user then subsequently progresses to a new Tutor version, Kubernetes attempts to update this label — but for `Deployment`, `ReplicaSet`, and `DaemonSet` resources, this is no longer allowed as of https://github.com/kubernetes/kubernetes/issues/50808. This causes `tutor k8s start` (at the `kubectl apply --kustomize` step) to break with errors such as:
```
Deployment.apps "redis" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"openedx-JIONBLbtByCGUYgHgr4tDWu1", "app.kubernetes.io/managed-by":"tutor", …
```
=> fix: Stop creating immutable resource label that breaks "tutor k8s" on Tutor version changes

docs/Makefile, docs/tutorials.rst, docs/tutorials/google-smtp.rst
The tutorial comes from the feedback of multiple users, including:
https://discuss.overhang.io/t/google-smtp-not-working/2143
=> docs: add tutorial on using Google Mail as an SMTP server

CHANGELOG.md, tutor/jobs.py
https://discuss.overhang.io/t/settheme-not-applied-to-preview-site/2144
=> Improvement: `settheme` now works with preview domain and `NGINX_HTTP_PORT`

CHANGELOG-nightly.md, tutor/templates/apps/openedx/settings/lms/production.py, tutor/templates/apps/openedx/settings/partials/common_all.py, tutor/templates/apps/openedx/settings/partials/common_cms.py
When HTTPS was not enabled, it was not possible to login to the LMS in some browsers, such as Brave.
- The sessionid cookie was being set with SameSite=None.
- That's because we were setting the DCS_SESSION_COOKIE_SAMESITE but not the
SESSION_COOKIE_SAMESITE setting.
- The DCS_* settings are ignored since edx-platform no longer makes use of
django-cookies-samesite.
Close https://github.com/openedx/build-test-release-wg/issues/110
=> fix: insecure http authentication in LMS

CHANGELOG-nightly.md, setup.py
Python 3.5 has reached end of life in September 3.5. Anyway, Tutor was not
compatible because some dev dependencies, such as astroid 2.8.3, are no longer
available in 3.5.
This means that we can now start using many python 3.6 niceties, such as
f-strings \o/
=> chore: drop python 3.5 compatibility

CHANGELOG.md, tutor/commands/images.py
Previously, `tutor images build doesnotexist` was a no-op. This was
counter-intuitive -- in particular, when users have a typo in their command.
Now, the command fails if the corresponding image was not found.
See discussion: https://discuss.overhang.io/t/return-something-when-tutor-images-build-contains-a-typo/2174
=> feat: fail `images build/pull/push` commands on incorrect image arg

Makefile, tests/test_config.py, tests/test_env.py, tests/test_plugins.py, tutor/bindmounts.py, tutor/commands/config.py, tutor/commands/k8s.py, tutor/commands/local.py, tutor/commands/plugins.py, tutor/config.py, tutor/env.py, tutor/interactive.py, tutor/templates/config/base.yml, tutor/templates/config/defaults.yml
Previously, configuration management was very confusing because we kept mixing
"base" and "defaults" configuration:
- It was difficult to make the difference between core settings that were
necessary (e.g: passwords) as opposed to others that could simply be
defaulted to.
- The order of settings in config.yml mattered: config entries that depended on
other needed to be defined later. As a consequence, Tutor was not compatible
with Python 3.5, where dict entries are not sorted.
This is a major refactor but it should not (:crossed_fingers:) have backward incompatible changes.
=> refactor: clarify configuration management

CHANGELOG-nightly.md, docs/k8s.rst, tutor/commands/k8s.py, tutor/templates/k8s/services.yml
See the changelog for a detailed review of changes.
Close #532, except for this item:
>  Somehow, find a way to run in non-production mode on a local cluster. If not, we should not be asking the user if they want to run in non-production mode during tutor save -i.
I think that we should stop asking the user whether they want to run in production when they run `tutor k8s quickstart`, but I'd like to merge #537 before we make this change. I'll open another PR later.
cc @fghaas who started the conversation around these issues.
=> Multiple improvements to the Caddy load balancer in Kubernetes

CHANGELOG.md, tutor/templates/build/openedx/Dockerfile
When I tried building the `openedx` image on an ARM64 Mac, this line of the `Dockerfile` failed:
https://github.com/overhangio/tutor/blob/19157d94bca8a4998271082045448a919bcd4761/tutor/templates/build/openedx/Dockerfile#L81-L82
[The error message was that `libgeos` could not be found while installing `shapely`.](https://stackoverflow.com/questions/19742406/could-not-find-library-geos-c-or-load-any-of-its-variants)
I am not sure why this would differ between arm64 and amd64 builds, but in any case this PR fixes the issue.
With this fix, `tutor images build openedx` works and is sufficient to build the LMS image for the `arm64/v8` architecture without any other changes.
=> Fix arm64 image build - open-release/lilac.3

CHANGELOG-nightly.md, tutor/templates/hooks/lms/init, tutor/templates/local/docker-compose.jobs.yml
In the latest master version of Open edX (post-Maple), some course data has moved from MongoDB to MySQL. There is [a data migration which automatically moves this data over](https://github.com/edx/edx-platform/blob/master/common/djangoapps/split_modulestore_django/migrations/0002_data_migration.py), but it currently causes Tutor nightly `tutor local init` to fail when running migrations, because MongoDB is not running.
Without this fix, `tutor local init` fails on Tutor nightly.
=> Bugfix: A migration on nightly/master Open edX now requires MongoDB

docs/tutorials.rst, docs/tutorials/arm64.rst
Per the discussion on https://github.com/overhangio/tutor/issues/510 and https://github.com/overhangio/tutor/pull/543, here is a tutorial for the docs that explains how to run Tutor on ARM-based systems like M1 MacBooks.
I wasn't sure exactly where to put it, so let me know if it should be moved somewhere else.
Screenshot:
=> Tutorial: how to run Tutor on ARM-based systems

CHANGELOG.md, docs/_release_description.md, docs/configuration.rst, docs/dev.rst, docs/index.rst, docs/install.rst, docs/quickstart.rst, setup.py, tests/test_env.py, tutor/commands/k8s.py, tutor/commands/local.py, tutor/commands/upgrade/common.py, tutor/commands/upgrade/k8s.py, tutor/commands/upgrade/local.py, tutor/env.py, tutor/templates/k8s/deployments.yml, tutor/templates/local/docker-compose.yml
When upgrading from Lilac, all services break with the following error:
Service "***" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
Upgrading deployments fails as well:
Deployment.apps "***" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"openedx-********", "app.kubernetes.io/managed-by":"tutor", "app.kubernetes.io/name":"***", "app.kubernetes.io/part-of":"openedx"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
That's because deployments and services need to be deleted as part of the Maple
upgrade. So that's what we do as part of `tutor k8s upgrade --from=lilac`. And
we take the opportunity to:
1. Run upgrade as part of quickstart, when necessary. …
=> fix: upgrade from Lilac on k8s

CHANGELOG-nightly.md, tutor/templates/build/openedx/Dockerfile
In the LMS/CMS Dockerfile, the env var STUDIO_CFG is set
in order to point CMS at its configuration json/yaml file.
Since https://github.com/edx/edx-platform/pull/29534
(which introduced 0013-cms-vs-studio.rst), the STUDIO_CFG
variable has been deprecated in favor of CMS_CFG.
This change updates the Dockerfile to reflect the new
preferred environment variable.
The only noticeable impact of this change is that it
will remove a depreation warning from Django startup
for tutor uses running off of Open edX master.
~This will **not work** with Maple, since Maple was cut before the CMS_CFG environment variable was introduced. This shouldn't be merged until no further Maple-supporting point releases are planned to be cut from Tutor master.~
Will be merged to `nightly` branch so that this ^ isn't …
=> chore: set CMS_CFG instead of STUDIO_CFG

CHANGELOG.md, tutor/templates/local/docker-compose.jobs.yml
Currently running `tutor local importdemocourse` would fail when the platform is not up. I'm a bit curious why we need redis though, as I'm not sure what role it plays.
=> fix `tutor local importdemocourse`

CHANGELOG.md, tutor/templates/apps/openedx/settings/partials/common_lms.py
The LazyStaticAbsoluteUrl object was breaking bulk emails again with the
following stacktrace:
2022-01-11 13:50:10,591 ERROR 12 [celery.app.trace] [user None] [ip None] trace.py:255 - Task lms.djangoapps.instructor_task.tasks.send_bulk_course_email[26b93357-018a-408f-b3f7-b69722447c5b] raised unexpected: EncodeError(TypeError('Object of type LazyStaticAbsoluteUrl is not JSON serializable'))
File "/openedx/venv/lib/python3.8/site-packages/kombu/serialization.py", line 50, in _reraise_errors
yield
File "/openedx/venv/lib/python3.8/site-packages/kombu/serialization.py", line 221, in dumps
payload = encoder(data)
File "/openedx/venv/lib/python3.8/site-packages/kombu/utils/json.py", line 69, in dumps
return _dumps(s, cls=cls or _default_encoder,
File …
=> fix: broken bulk emails because of LazyStaticAbsoluteUrl (again)

CHANGELOG.md, tutor/templates/apps/caddy/Caddyfile
Previously, we were redirecting all /*favicon.ico requests to the default
favicon. This meant that the favicon might not necessarily be correctly themed,
most notably in MFEs. Here, we resolve this issue by redirecting to the
theme-agnostic theming/asset/* url. Also, we restrict the overly generic regexp
for favicon url matching. We verified that we did not miss any url by running
the following command on the demo server:
tutor local logs caddy | grep --only-matching "host.*favicon.ico" | sort | uniq
=> fix: display themed favicon across all apps

CHANGELOG.md, tutor/templates/apps/openedx/settings/lms/development.py
In development, it was no longer possible to authenticate to the lms. Ater
signing in, the session ID could not be dropped, and thus the user was not
signed in, although no error was logged -- just a warning in the browser
console.
This problem was caused by the fact that the SameSite policy was set to "None"
in development.
=> fix: lms authenticaton in development

docs/configuration.rst
See: https://discuss.overhang.io/t/default-smtp-configuration-timeout/2367
=> docs: fix smtp port default value

docs/plugins/api.rst
Clarify how plugin authors can access the Click context, and from it the Tutor configuration, from the function implementing a plugin command.
Reference:
https://discuss.overhang.io/t/how-does-a-plugin-command-access-the-tutor-configuration/2372
=> docs: Explain passing the Click context to a plugin command

CHANGELOG.md, tutor/templates/kustomization.yml
Caddy was not properly starting because its associated configmap was not
starting.
Close #577.
=> fix: `k8s start caddy` command

tutor/templates/build/openedx/Dockerfile
See: https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-4-0
=> chore: resolve "deprecated django-admin.py is deprecated" warning

CHANGELOG.md, tutor/commands/k8s.py, tutor/commands/local.py
=> fix: "unexpected keyword argument" during quickstart upgrade

CHANGELOG.md, tutor/templates/build/openedx/Dockerfile
The version of dockerize that shipped with the "openedx" image was not
compatible with arm64. The original project is unmaintained, but there
is a fork that provides a version that is compatible with arm64.
Close #591
=> fix: dockerize on arm64

docs/whatnext.rst
See: https://discuss.overhang.io/t/demo-test-course-vs-edx-demo-course/2549
=> docs: fix demo course link

CHANGELOG-nightly.md, tutor/templates/k8s/deployments.yml, tutor/templates/local/docker-compose.yml
```
Before edx-platform was upgraded to Celery 5, lms-worker and
cms-worker could be invoked using this syntax:
celery worker --app=APP <args> --maxtasksperchild=N <args>
Since the recent Celery 5 upgrade (edx-platform commit 0588c92),
though, this fails with the messages:
You are using `--app` as an option of the worker sub-command:
celery worker --app celeryapp <...>
The support for this usage was removed in Celery 5.0.
Instead you should use `--app` as a global option:
celery --app celeryapp worker <...>
and:
Error: No such option: --maxtasksperchild
(Possible options: --max-memory-per-child, --max-tasks-per-child)
So, this commit changes the lms-worker and cms-worker invocations to:
celery --app=APP <args> --max-tasks-per-child=N <args>
```
As of 2022-03-18, the official …
=> fix: lms-worker/cms-worker command update for Celery 5

CHANGELOG.md, tutor/commands/k8s.py, tutor/commands/local.py
- [Bugfix] Fix "evalsymlink failure" during `k8s quickstart` (#611).
- [Bugfix] Fix "TypeError: upgrade() got an unexpected keyword argument 'non_interactive'" during `local upgrade`.
See:
https://github.com/overhangio/tutor/issues/611#issuecomment-1076536420
https://discuss.overhang.io/t/upgrade-error-upgrade-got-an-unexpected-keyword-argument-non-interactive/2582
=> fix broken quickstart

CHANGELOG.md, README.rst, docs/configuration.rst, docs/dev.rst, docs/faq.rst, docs/install.rst, docs/intro.rst, docs/k8s.rst, docs/local.rst, docs/plugins.rst, docs/plugins/api.rst, docs/plugins/gettingstarted.rst, docs/quickstart.rst, docs/troubleshooting.rst, docs/tutor.rst, docs/tutorials/arm64.rst, docs/tutorials/datamigration.rst, docs/tutorials/google-smtp.rst, docs/tutorials/multiplatforms.rst, docs/tutorials/nightly.rst, docs/tutorials/podman.rst, docs/tutorials/proxy.rst, docs/tutorials/scale.rst, docs/tutorials/theming.rst, docs/whatnext.rst, tutor/commands/plugins.py, tutor/plugins.py, tutor/templates/k8s/deployments.yml
Hi Regis.
I always read the tutor’s documentation and every time, I saw some small issues in the grammar, it bothers me, cause the tutor is such a great tool and it should have the highest standards. so, on a weekend, I checked all of the documentation for proofreading and grammar issues using my knowledge and Grammarly.
these changes happened in this PR:
```
lots of "the" and commas were added.
the wrong usage of "by" changed to "with".
some words were spelled wrong. 
```
Lots of words changed to the original form. like:
```
url -> URL
kubernetes -> Kubernetes
http -> HTTP
https -> HTTPS
html -> HTML
nginx -> Nginx
memecache -> Memecache
mongodb -> MongoDB
pypi -> PyPI
redis -> Redis
rabbitmq -> RabbitMQ
```
I noticed that you use "s" instead of "z" in some words, like customise and …
=> Proofreading and fixing minor typos of documentations

setup.py
The version of the nightly python package should not include the "-nightly"
suffix. That's because when we `pip install -e` tutor plugins, pip also
installs the latest tutor release, as part of the requirements. This overrides
the local (nightly) installation of tutor.
See: https://app.slack.com/client/T02SNA1T6/C02V3GHE3UP
=> fix: nightly package version

tutor/commands/upgrade/k8s.py, tutor/commands/upgrade/local.py
An `echo_info` message in the upgrade commands rendered MongoDB as "MongDB". Trivial fix.
=> fix: Fix typo ("MongDB")

CHANGELOG-nightly.md, requirements/plugins.txt
This fixes https://github.com/overhangio/2u-tutor-adoption/issues/41. Before this PR, Tutor Nightly users needed to install all the official plugins by hand (unlike Tutor Stable users, who have the plugins bundled in for them). After this PR, simply running `pip install -e "./tutor[full]"` on the nightly branch will install Tutor Nightly as well as Nightly versions of all plugins
Documentation changes have been made in a separate PR, so that they can be merged to `master` and reflected on the official documentation site as soon as this is merged to `nightly`: https://github.com/overhangio/tutor/pull/631
From Tutor's `nightly` branch:
pip uninstall --yes tutor-discovery tutor-mfe  # Or any other plugins
tutor plugins list # Should be missing tutor-discovery and tutor-mfe
pip install -e …
=> build: NIGHTLY ONLY: install nightly branches of official plugins

CHANGELOG.md, docs/configuration.rst, tutor/templates/build/openedx/Dockerfile, tutor/templates/config/defaults.yml
Previously, the only way for Tutor users to use a fork of `edx-platform` or a custom NPM registry was to use build args during the image build.
This is suboptimal in the case of automatically building images from CI pipelines, which may want to auto-detect when an image needs to be rebuilt based on `config.yml` changes.
In addition, the `EDX_PLATFORM_VERSION` build argument can already be set via a corresponding `config.yml` parameter (`OPENEDX_COMMON_VERSION`), so it's reasonable to follow that precedent and also introduce `config.yml` parameters to correspond with the `EDX_PLATFORM_REPOSITORY` and `NPM_REGISTRY` build arguments.
Thus, introduce two new configuration parameters:
- `OPENEDX_PLATFORM_REPOSITORY`
- `OPENEDX_NPM_REGISTRY`
These parameters can now optionally be used instead …
=> feat: Make the platform repository and NPM registry configurable from config.yml

docs/_release_description.md, docs/download/pip.rst, docs/install.rst, docs/tutorials/nightly.rst
This PR is a companion to https://github.com/overhangio/tutor/pull/626. In that PR, we change Nightly's `[full]` installation to point to the `nightly` branches of official plugins on GitHub (instead of the stable version of plugins from PyPI). This allows Nightly users to make use of the plugins-included `[full]` installation. In this PR, we update the documentation to reflect the improvement.
Blocked by https://github.com/overhangio/tutor/pull/626
This PR is part of https://github.com/overhangio/2u-tutor-adoption/issues/41
See **Testing** on https://github.com/overhangio/tutor/pull/626
I included a ride-along docs improvement in a second commit: **docs: wrap tutor[full] in quotes for zsh compatibility**. Check out its commit message for details.
=> docs: update Nightly docs to reference [full] installation 

CHANGELOG.md, tutor/commands/k8s.py
Previously, the `k8s exec` command did not support unknown "--options". This
made it impossible to launch, say, a django shell in the lms container.
While implementing this feature we saw an opportunity to simplify the way jobs
are handled in the k8s commands.
Close #636.
Another related issue is: https://github.com/overhangio/2u-tutor-adoption/issues/52
=> feat: run `tutor k8s exec ...` commands with multiple args

docs/configuration.rst, tutor/templates/build/openedx/Dockerfile, tutor/templates/config/defaults.yml
PR #619 set the `EDX_PLATFORM_VERSION` build arg's default to `OPENEDX_COMMON_VERSION`. While this works fine for setting a non-default branch to run edx code from (say, `master`), it may break if the user sets `OPENEDX_COMMON_VERSION` to a branch or tag name that does not exist upstream in repositories *other than* `EDX_PLATFORM_REPOSITORY`.
Thus, introduce a separate configuration parameter, `EDX_PLATFORM_VERSION`, to match the build arg of the same name. Set its default to `OPENEDX_COMMON_VERSION`.
This way, the user can deploy an arbitrarily-named fork of `edx-platform`, while retaining the default  `OPENEDX_COMMON_VERSION` (like, for example `open-release/maple.3`) for everything else.
=> fix: Correct EDX_PLATFORM_VERSION default for local edx-platform forks

tutor/templates/hooks/mysql/init
MySQL 8 drop the support for creating users by executing `GRANT ALL`. This commit splits the user creation and permission granting, therefore the newer MySQL versions are supported too.
MySQL 8 is (mostly) [supported by edx-platform](https://github.com/openedx/configuration/blob/1cdb0347c5e25dd88c4a64634ea931dc46d4f3cd/playbooks/roles/mysql/tasks/mysql.yml#L93-L98), though there are some leftovers from [fully supporting](https://github.com/openedx/platform-roadmap/issues/119) it.
* N/A
1. Setup a new tutor instance
None
=> [SE-5427] fix: ensure mysql8 compatibility

CHANGELOG.md, docs/dev.rst, docs/install.rst, docs/intro.rst, tests/test_config.py, tutor/commands/config.py, tutor/commands/dev.py, tutor/commands/k8s.py, tutor/commands/local.py, tutor/interactive.py
Fixes https://github.com/overhangio/2u-tutor-adoption/issues/58
There are three commits. The first two just add some supplementary doc updates, which I could remove from this changeset if they don't seem like a good idea. The third commit introduces `tutor dev quickstart` along with the most critical documentation updates.
I wanted to tailor `tutor dev quickstart` to the development use case, so there are some differences between it and `tutor local quickstart`:
1. it starts dev containers instead of local ones (duh),
2. it builds the openedx-dev image, and
3. it assumes No for the the "Is this a production platform?" question,
4. it offers to import the demo course and create a supseruser.
Difference **1** is the only thing that _really_ needed to be changed, so if there are objections …
=> feat: introduce 'tutor dev quickstart' (also, some extra docs)

CHANGELOG.md, docs/dev.rst, docs/tutorials/nightly.rst, docs/tutorials/plugin.rst, docs/tutorials/theming.rst, tutor/commands/dev.py, tutor/templates/dev/docker-compose.yml
Resolves https://github.com/overhangio/2u-tutor-adoption/issues/61
Blocked by these plugin PRs:
* https://github.com/overhangio/tutor-mfe/pull/46
* https://github.com/overhangio/tutor-discovery/pull/29
* https://github.com/overhangio/tutor-ecommerce/pull/23
* https://github.com/overhangio/tutor-notes/pull/10
* https://github.com/overhangio/tutor-forum/pull/4
* https://github.com/overhangio/tutor-xqueue/pull/7
There are still a couple references to `tutor dev runserver` in the official plugins, but totally scrubbing them would require moving the plugins to the V1 API and implementing the `COMPOSE_MOUNTS` filter. I figure that we can punt that work to https://github.com/overhangio/2u-tutor-adoption/issues/26.
See commit message / changelog for details.
=> feat: deprecate `runserver` in favor of `start`

tests/commands/test_compose.py, tutor/commands/compose.py, tutor/commands/dev.py
I didn't include a changelog entry, as this fixes a feature that hasn't yet been released.
Also included, in a second commit: a drive by fix to the `runserver` deprecation warning.
=> fix: `--mount` should accept service names with hyphens

CHANGELOG.md, tutor/templates/apps/openedx/settings/partials/common_lms.py
When launching a new instance of Tutor just now, I had the LMS fail to start (Studio worked fine). The error was:
```
lms_1 | Traceback (most recent call last):
lms_1 |   File "lms/wsgi.py", line 18, in <module>
lms_1 |     import lms.startup as startup  # lint-amnesty, pylint: disable=wrong-import-position
lms_1 |   File "/openedx/edx-platform/./lms/startup.py", line 10, in <module>
lms_1 |     settings.INSTALLED_APPS  # pylint: disable=pointless-statement
lms_1 |   File "/openedx/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
lms_1 |     self._setup(name)
lms_1 |   File "/openedx/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
lms_1 |     self._wrapped = Settings(settings_module)
lms_1 |   File …
```
=> fix: race condition could cause mkdirs() to fail with "dir exists"

CHANGELOG.md, docs/dev.rst, tests/commands/test_compose.py, tests/commands/test_local.py, tutor/commands/compose.py, tutor/commands/k8s.py, tutor/commands/local.py, tutor/commands/plugins.py
`copyfrom` copies data from a container to the local filesystem. It's similar
to bindmount, but less clunky, and more intuitive. Also, it plays along great
with `--mount`. Eventually we'll just get rid of the `bindmount` command and
the `--volume` option.
=> feat: add `dev/local copyfrom` commands

CHANGELOG.md, docs/tutorials/arm64.rst, tutor/commands/compose.py, tutor/commands/dev.py, tutor/commands/local.py, tutor/hooks/consts.py
Running `local start` while a dev platform is still running is a common sourse
of mistakes. Here we introduce a new action to automatically stop local and dev
projects whenever a project with a different name is started.
=> feat: `local stop` on `dev start` (and vice versa)

CHANGELOG.md, tutor/templates/build/openedx/Dockerfile
see discussion: https://discuss.overhang.io/t/missing-js-css-files-missing-from-openedx-docker-image-in-studio/2629
see pull request: https://github.com/openedx/edx-platform/pull/30309
(thanks @uetuluk!)
=> fix: broken file upload in studio

tutor/hooks/consts.py
Fixes a copy-paste error in the docs "pulled" -> "pushed" in `IMAGES_PUSH` filter docstring.
=> docs: fix copy-paste error in docstring

docs/plugins/examples.rst
I was reading the new plugin documentation to migrate from v0 to v1 and see this typo.
I copied and pasted the example to test and it took me a few minutes to find the error. :grimacing:
I don't know if just this change is a valid PR ...
[Documentation link](https://docs.tutor.overhang.io/plugins/examples.html#skip-email-validation-for-new-users)
=> docs: fix typo in skip email validation plugin example

README.rst
Repair plugins broken link in the Features section of README file.
=> docs: fix plugins broken link

CHANGELOG.md, tutor/templates/apps/openedx/settings/partials/common_cms.py
Login to the studio was causing a 500 error, although the user was correctly
connected. See the issue description here:
https://github.com/openedx/build-test-release-wg/issues/114
The error was caused by the fact that both LMS and CMS session cookies were
being sent to the CMS and the LMS session cookie was considered the "right"
one. To clarify between both cookies, we need to have different session cookie
names between the lms and the cms. This requirement was actually documented in
step 5 of this authentication migration document:
https://github.com/openedx/edx-platform/blob/master/docs/guides/studio_oauth.rst#migration
For more information, have a look at the live stream during which this issue
was debugged: https://youtu.be/m3t1U_y6F64
Close …
=> fix: 500 error during studio login

CHANGELOG.md, tutor/templates/k8s/deployments.yml
When a Pod associated with a Deployment is updated (for example, due to a change to its ConfigMap, or an updated image reference), Kubernetes uses a ReplicaSet to spin up a Pod with the new configuration, and once it is up, it tears down the old one.
In case of the Caddy Deployment, this is complicated by the fact that it uses a PersistentVolumeClaim (PVC), whose corresponding volume uses a Read/Write-Once (RWO) configuration. This means that it can only be used by multiple Pods if all those Pods all run on the same Kubernetes worker node.
In order to enable rolling upgrades for the Caddy Deployment, we need to ensure that its replacement Pod is scheduled on the same node as the original Pod.
Thus, add a pod affinity rule that will force exactly that behavior.
The other Tutor services …
=> fix: Enable rolling updates for the Caddy deployment in multi-node Kubernetes

docs/tutorials/datamigration.rst
The default user in the mysql container is `openedx`,
so using the root mysql password leads to an auth failure.
Instead, we should run the mysql dump using the
user configured in MYSQL_ROOT_USERNAME.
Other than whitespace changes, the only substantive change is the addition of:
```
-u "$(tutor config printvalue MYSQL_ROOT_USERNAME)"
```
=> docs: specify root username in mysql dump instructions

.github/ISSUE_TEMPLATE/question.md, README.rst, docs/dev.rst, docs/index.rst, docs/troubleshooting.rst, docs/tutor.rst, docs/tutorials/index.rst, docs/whatnext.rst, setup.py
Now that Tutor is the official community installation for Open edX, it no
longer makes sense to host a forum that is separate from the general Open edX
forum. Moving conversations there will encourage cross-communication between
projects and maintainers. This change is part of a larger overhaul described in
this Tutor enhancement proposal (TEP):
https://discuss.overhang.io/t/tep-rethinking-the-tutor-maintainers-program/2724
In the future, plugin maintainers should point their users to the Open edX
forum as well. They are encouraged to create dedicated "tutor-pluginnname" tags
on the forum and to set their notification level to "watching".
=> docs: move forum to discuss.openedx.org

CHANGELOG.md, docs/dev.rst, tutor/templates/build/openedx/Dockerfile
Contrary to what we might expect, `npm install` does not install pinned
requirements from a project's package-lock.json. That's the responsibility of
`npm ci`: https://docs.npmjs.com/cli/v8/commands/npm-ci
Running `npm ci` is also *much* faster than `npm install`, so that's a huge win.
See this issue for reference: https://github.com/openedx/frontend-wg/issues/100
=> feat: pinned nodejs requirements with `npm ci`

CHANGELOG.md, tutor/plugins/__init__.py
When running multiple concurrent versions of a plugin there are sometimes
version conflicts that prevent the plugin from being loaded. Prior to v1, Tutor
was correctly ignoring plugins that could not be loaded. During the transition
to v1 we lost that feature because we only captured TutorErrors.
=> fix: ignore plugins that cannot be loaded

CHANGELOG.md, docs/reference/patches.rst, tutor/templates/build/openedx/Dockerfile
Building on the work done in https://github.com/overhangio/tutor/pull/427. This PR allows you to configure the uWSGI buffer size in `config.yml`
From the [uWSGI docs](https://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html):
> If you start receiving “invalid request block size” in your logs, it could mean you need a bigger buffer. Increase it (up to 65535) with the buffer-size option.
One of our deployments uses SAML for authentication so the request headers and body for the authentication requests can get pretty verbose. We started receiving the "invalid request block size" error, so we bumped the buffer size to `32768`.
Does it make sense to bump the default from `8192` to `32768` (or something else)?
=> feat: patch for openedx-dockerfile-final

CHANGELOG.md, tests/commands/test_config.py, tests/test_env.py, tutor/commands/config.py, tutor/env.py, tutor/hooks/consts.py
When rendering theme files in a plugin, the *.scss files are stored in a
"partials" subdirectory, which was ignored by the environment rendering logic.
To render these files, we move the path ignoring logic to a filter, which is a
list of regular expressions. Values in this filter can be overridden by another
filter.
See the corresponding issue in the indigo theme plugin:
https://github.com/overhangio/tutor-indigo/issues/24
=> feat: render files in ignored directories

docs/install.rst
I noticed `pip uninstall -y tutor` will not uninstall the plugins, so I made this PR. I know it's ugly, but I don't find any other way of doing it. Let me know if there are better choices 😊
=> docs: complete uninstalling of tutor

CHANGELOG.md, tutor/templates/dev/docker-compose.yml
Celery workers failed to start in development with the following stacktrace:
cms-worker_1                 | Traceback (most recent call last):
cms-worker_1                 |   File "/openedx/venv/bin/celery", line 8, in <module>
cms-worker_1                 |     sys.exit(main())
cms-worker_1                 |   File "/openedx/venv/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
cms-worker_1                 |     _main()
cms-worker_1                 |   File "/openedx/venv/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
cms-worker_1                 |     cmd.execute_from_commandline(argv)
cms-worker_1                 |   File "/openedx/venv/lib/python3.8/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
cms-worker_1 …
=> fix: celery workers in dev

tutor/templates/apps/openedx/config/cms.env.yml
Add missing two spaces indentation to the features patches in the CMS configuration file.
This is causing a corrupt cms.env.yml configuration file.
Note that in the lms.env.yml template, the patches are properly indented.
=> Add missing indentation in cms feature patches

CHANGELOG.md, tutor/templates/build/openedx/Dockerfile
When reviewing Dockerfile recently, I noticed that the git apply patch lines (where I learned the GitHub .diff and .patch trick) were replaced by cherry-pick. I noticed from the [commit](https://github.com/overhangio/tutor/commit/ca3aabedce250ef5a34c9f89a6545d984cdef30c) that this is for a better git working dir. However, apparently fetching the whole repo (even with the `depth` option) is not elegant. After some research, I found that `git am` is a better choice.
=> [Improvement] Use `git am` instead of `cherry-pick` to simplify patching process

CHANGELOG.md, tutor/templates/apps/openedx/config/cms.env.yml
Incorrect format of cms.yml config file was causing the following error on course import:
cms-worker_1                 | Traceback (most recent call last):
cms-worker_1                 |   File "/openedx/edx-platform/cms/djangoapps/cms_user_tasks/tasks.py", line 53, in send_task_complete_email
cms-worker_1                 |     mail.send_mail(subject, message, from_address, [dest_addr], fail_silently=False)
cms-worker_1                 |   File "/openedx/venv/lib/python3.8/site-packages/django/core/mail/__init__.py", line 61, in send_mail
cms-worker_1                 |     return mail.send()
cms-worker_1                 |   File "/openedx/venv/lib/python3.8/site-packages/django/core/mail/message.py", line 284, in send
cms-worker_1                 |     return …
=> fix: email sending from cms

CHANGELOG.md, docs/dev.rst, tutor/templates/build/openedx/Dockerfile, tutor/templates/config/defaults.yml
- Exposes `PYTHONBREAKPOINT` as a Tutor configuration variable
- Sets `ENV PYTHONBREAKPOINT={{ PYTHONBREAKPOINT }}` in the openedx dockerfile
- Changes the docs to recommend using `breakpoint()`. Explains that `PYTHONBREAKPOINT` can be modified in order to use a custom debugger.
1. Build openedx: `tutor images build openedx`
2. Build openedx-dev: `tutor dev dc build`
3. Run bash in lms: `tutor dev run lms bash`
4. Within bash, check for `PYTHONBREAKPOINT`: `env | grep PYTHONBREAKPOINT`
And `make test`
Closes https://github.com/overhangio/2u-tutor-adoption/issues/45
=> Add PYTHONBREAKPOINT as exposed config variable

CHANGELOG.md, tutor/templates/build/openedx/Dockerfile
**Description**
This PR adds a commit that updates the problem with hint template so it works with newer python versions.
**Discussions**
https://github.com/openedx/edx-platform/pull/30570#issuecomment-1156420335
**How to test**
Refer to this [PR](https://github.com/openedx/edx-platform/pull/30585) for the testing instructions.
=> fix: update problem with hint according newer python versions

CHANGELOG.md, tutor/templates/hooks/lms/init
This PR fixes the dockerize wait command execution on SRV records by not waiting for the resource.
MongoDB clusters with connection string starting with `mongodb+srv` would connect to an cluster behind an SRV record. Since `dockerize` cannot "ping" SRV records, it waits until a timeout and the job fails.
N/A
<details>
<summary>job output</summary>
<pre>
2022/06/23 14:12:17 Ready: tcp://oc-stage-nyc3-mysql-do-user-9002811-0.b.db.ondigitalocean.com:25060.
MongoDB is using SRV records, so we cannot wait for it to be ready
Loading settings lms.envs.tutor.production
2022-06-23 14:12:24,768 WARNING 12 [py.warnings] [user None] [ip None] warnings.py:109 - /openedx/venv/lib/python3.8/site-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib; see the …
=> fix: skip waiting for mongodb SRV records

CHANGELOG.md, tutor/templates/build/openedx/Dockerfile
The actual merge of this into open-release/nutmeg.master is here:
https://github.com/openedx/edx-platform/pull/30716
=> fix: apply LTI 1.3 XBlock patch fix 3.4.7 over nutmeg.1

CHANGELOG.md, tutor/templates/build/openedx/Dockerfile, tutor/templates/dev/docker-compose.yml
Sometimes, the host user is root: this may happen when tutor is run with
"sudo" (which is not recommended) or on Windows. In such cases, building
the image should not fail, but default to a reasonable user. Also, when
we pass an invalid APP_USER_ID as a build arg, then we should fail with
an explicit message.
See this conversation:
https://discuss.overhang.io/t/problem-with-dev-image-build-useradd-uid-0-is-not-unique/2406
=> fix: build openedx-dev image when host user is root

CHANGELOG.md, tutor/__about__.py
- [Bugfix] Build openedx-dev Docker image even when the host user is root, for instance on Windows. (by @regisb)
- [Bugfix] Patch nutmeg.1 release with [LTI 1.3 fix](https://github.com/openedx/edx-platform/pull/30716). (by @ormsbee)
- [Improvement] Make it possible to override k8s resources in plugins using `k8s-override` patch. (by @foadlind)
=> v14.0.3 (2022-07-09)

docs/dev.rst
edx-platform's ./common/lib/xmodule/xmodule folder has been moved to
./xmodule. The test-running instructions needed to be updated in order
to account for this new top-level folder.
For context on the edx-platform change, see:
https://discuss.openedx.org/t/breaking-apart-edx-platforms-common-lib-folder
=> docs: update test-running guide with new top-level xmodule package

CHANGELOG.md, tutor/templates/kustomization.yml
Fix: tutor k8s start will succeed when `k8s-override` and `kustomization-patches-strategic-merge` aren't specified.
https://github.com/overhangio/tutor/issues/704
Starting with version 14.0.2, every time we tried to run `tutor k8s start`, we would receive the following error:
```
Run tutor k8s start
kubectl get namespaces openedx-prod
NAME           STATUS   AGE
openedx-prod   Active   49d
Namespace already exists: skipping creation.
kubectl apply --kustomize /home/runner/.local/share/tutor/env --wait --selector app.kubernetes.io/component=volume
error: trouble configuring builtin PatchStrategicMergeTransformer with config: `
paths:
- k8s/override.yml
`: patch appears to be empty; files=[k8s/override.yml], Patch=
Error: Command failed with status 1: kubectl apply --kustomize …
```
=> Fix: Issue 702: tutor k8s start fails with no PatchStrategicMerge

CHANGELOG.md, tests/commands/test_compose.py, tutor/commands/compose.py, tutor/hooks/consts.py
In certain code paths, such as in `tutor local quickstart`,
`process_mount_points` is called more than once in the same process,
causing mounts to be added to `COMPOSE_LOCAL[_JOBS]_TMP` redundantly.
As a result, docker-compose[.jobs].tmp.yml was occasionally being
rendered with duplicate volume specifiers. Some versions of Docker
Compose ignored this; other versions warned or threw an error.
In order to make `process_mount_points` tolerant to being called
multiple times, we wrap its volume-adding callbacks within a new
hooks context. This allows us to clear said hooks context every
time `process_mount_points` is called, essentially making the
function idempotent.
=> fix: avoid double-rendering mounts to docker-compose.tmp.yml

CHANGELOG.md, tutor/commands/k8s.py, tutor/commands/upgrade/k8s.py
Currently tutor waits for k8s pods to be ready by running the `kubectl wait` command like this:
`kubectl wait --namespace openedx --selector=app.kubernetes.io/name=elasticsearch --for=condition=ContainersReady --timeout=600s pod`
This works for the most part, however it fails if there are existing pods not in the correct state.
For example, if a the Elastic Search pod is Evicted, you can end up with a pod list that looks list this if the nodes were experiencing memory pressure.
```
elasticsearch-78dcff9c9d-69lqp   0/1     Evicted     0          13h
elasticsearch-78dcff9c9d-clp66   0/1     OOMKilled   0          16h
elasticsearch-78dcff9c9d-g28bp   0/1     Evicted     0          13h
elasticsearch-78dcff9c9d-hngsd   1/1     Running     0          13h
elasticsearch-78dcff9c9d-jx2n7   0/1 …
```
=> fix: k8s wait for deployments instead of pods to determine readiness

CHANGELOG.md, tests/test_utils.py, tutor/utils.py
Whenever Tutor executes a shell command, it logs out said
command in order to aid in end user understanding/debugging.
In some cases (notably, when running jobs in containers)
the logged command was not accurately quoted. The command
was run correctly, because it was passed in pieces to
``subprocess.Popen``, which correctly joins the pieces together
into a valid POSIX shell command; however, the logged version
of the command was constructed by simply joining the pieces
with spaces. This usually works, but breaks down when running
complex shell commands with nested quoting.
This commit changes the logging to use ``shlex.join``, which
joins command pieces together in a POSIX-compliant way,
presumably the same way as ``subprocess.Popen``.
Example:
tutor local importdemocourse
runs the shell …
=> fix: accurately log shell commands when running jobs

CHANGELOG.md, tests/commands/test_compose.py, tutor/commands/compose.py, tutor/commands/dev.py, tutor/commands/local.py, tutor/hooks/consts.py, tutor/utils.py
The -m/--mount option makes it possible to bind-mount volumes at runtime. The
volumes are declared in a local/docker-compose.tmp.yml file. The problem with
this approach is when we want to bind-mount a volume to a service which is
specific to the dev context. For instance: the "learning" service when the MFE
plugin is enabled.
In such a case, starting the service triggers a call to `docker-compose stop`
in the local context. This call fails because the "learning" service does not
exist in the local context. Note that this issue only seems to occur with
docker-compose v1.
To resolve this issue, we create two additional filters for
the dev context, which emulate the behaviour of the local context. With this approach, we convert the -m/--mount arguments right after they are parsed. Because …
=> fix: bind-mount in dev-specific services

CHANGELOG-nightly.md, tutor/commands/dev.py
This PR was [originally authored](https://github.com/overhangio/tutor/pull/710) by @Carlos-Muniz. I'm re-opening it against the nightly branch so that this breaking change goes out along with the Olive release.
___________________
This PR removes the implementation of `tutor dev runserve`r. It is being removed in favor of using `tutor dev start`.
This PR should be merged last after each of the following have been merged:
* https://github.com/overhangio/tutor-ecommerce/pull/31
* https://github.com/overhangio/tutor-forum/pull/8
* https://github.com/overhangio/tutor-notes/pull/13
* https://github.com/overhangio/tutor-xqueue/pull/9
Closes https://github.com/overhangio/2u-tutor-adoption/issues/26
=> feat: remove the implementation of dev runserver

CHANGELOG.md, tutor/templates/build/openedx/Dockerfile
Strings could not be pulled from transifex because the file names were
incorrect. This is now fixed and we are now able to pull the i18n strings from
the nutmeg.2 tag.
=> feat: upgrade i18n openedx strings to nutmeg.2

CHANGELOG-nightly.md, README.rst, docs/configuration.rst, docs/dev.rst, docs/gettingstarted.rst, docs/index.rst, docs/install.rst, docs/intro.rst, docs/k8s.rst, docs/local.rst, docs/plugins/intro.rst, docs/plugins/v0/gettingstarted.rst, docs/quickstart.rst, docs/troubleshooting.rst, docs/tutorials/google-smtp.rst, docs/tutorials/nightly.rst, docs/tutorials/oldreleases.rst, docs/tutorials/plugin.rst, docs/whatnext.rst, tests/commands/test_local.py, tutor/commands/dev.py, tutor/commands/k8s.py, tutor/commands/local.py, tutor/config.py
These changes renames all mentions of `quickstart` to `launch`
found in the code and documentation.
Acceptance Criteria:
This PR is related to the following PRs:
- https://github.com/overhangio/tutor-ecommerce/pull/33
- https://github.com/overhangio/tutor-forum/pull/9
- https://github.com/overhangio/tutor-android/pull/4
- https://github.com/overhangio/tutor-discovery/pull/35
- https://github.com/overhangio/tutor-mfe/pull/60
- https://github.com/overhangio/tutor-xqueue/pull/12
Closes https://github.com/overhangio/2u-tutor-adoption/issues/53
=> feat: rename quickstart to launch

CHANGELOG.md, Makefile, requirements/plugins.txt, tutor/plugins/v0.py
The richie plugin was transferred to the openfun GitHub org. As a consequence, it is no longer part of the list of official plugins.
See: https://github.com/overhangio/tutor-contrib-richie/pull/5
=> depr: richie plugin is no longer official

tutor/templates/build/openedx/Dockerfile
The local requirements files does not exist since local requirements were all removed from the edx-platform repo. As a consequence, the nightly build was broken.
=> fix: edx-platform requirement installation

docs/local.rst
Running config save --interactive doesn't create a config.yml file in the current directory. It instead creates it in the project root.
=> Fix incorrect information about running config save --interactive

docs/tutorials/arm64.rst
It looks like this was resolved in https://github.com/overhangio/tutor-mfe/pull/42
=> Remove warning about building tutor-mfe on ARM systems

CHANGELOG-nightly.md, tutor/templates/build/openedx/Dockerfile
The `compilejsi18n` command was failing during image building because the Open-edX package was not installed properly. The reason for that was an earlier change where we got rid of the `pip install -r requirements/edx/local.in` command. Installing the Open-edX package was part of this requirement file.
The local.in requirements file no longer exists, but we still need to `pip install -e .` the edx-platform repo. To run this command we need both the edx-platform repo and the virtualenv.
The good news is that there are no more local requirements in the base.txt requirements file. This means that we no longer have to COPY the edx-platform repo in the requirements installation step. Thus, changes in edx-platform will no longer trigger a rebuild of the pip requirements; this means that …
=> nightly: fix: installation of local requirements

CHANGELOG.md, tutor/templates/apps/caddy/Caddyfile
Compressing assests would lead to readuce transfer size.
As testing with frontend-app-learning/Olive, the network traffic
before was about ~4MB, after this it became ~1MB.
This change was suggested by Google Lighthouse[1], there are of
course more suggestion but this was one the easiest and one of most
impactful.
Also check orignal PR overhangio/tutor-mfe/pull/64 for more
info.
[1]: https://web.dev/uses-text-compression
=> feat: use encode gzip for caddy

CHANGELOG.md, docs/Makefile, docs/conf.py, docs/reference/api/hooks/actions.rst, docs/reference/api/hooks/filters.rst, requirements/base.txt, requirements/dev.in, requirements/dev.txt, requirements/docs.txt, tests/hooks/test_actions.py, tests/hooks/test_filters.py, tests/test_config.py, tests/test_env.py, tutor/commands/cli.py, tutor/commands/compose.py, tutor/commands/images.py, tutor/config.py, tutor/env.py, tutor/hooks/actions.py, tutor/hooks/consts.py, tutor/hooks/filters.py, tutor/jobs.py, tutor/plugins/__init__.py, tutor/plugins/v0.py, tutor/templates/apps/openedx/settings/partials/common_all.py, tutor/types.py
Now that the mypy bugs have been resolved, we are able to define more precisely and cleanly the types of Actions and Filters.
Moreover, can now strongly type named actions and hooks (in consts.py). With such a strong typing, we get early alerts of hooks called with incorrect arguments, which is nothing short of awesome :)
This change breaks the hooks API by removing the `context=...` argument. The reason for that is that we cannot insert arbitrary arguments between `P.args, P.kwargs`: https://peps.python.org/pep-0612/#the-components-of-a-paramspec
> A function declared as def inner(a: A, b: B, *args: P.args, **kwargs:
> P.kwargs) -> R has type Callable[Concatenate[A, B, P], R]. Placing
> keyword-only parameters between the *args and **kwargs is forbidden.
Getting the documentation to …
=> feat: strongly typed hooks

CHANGELOG.md, tutor/commands/compose.py, tutor/hooks/consts.py
When typing `tutor local run --mount /path/to/edx-pl<TAB>`, the mount option should be auto-completed to the full edx-platform repo path. That is, if shell completion is enabled:
https://docs.tutor.overhang.io/install.html#shell-autocompletion
Here, we make sure that the implicit form of the `--mount` argument is properly auto-completed. We are unable to get completion to work in the explicit form, because args that include colons do not even reach the `shell_completion` method.
=> feat: auto-complete `--mount` args

tests/test_env.py, tutor/commands/jobs.py, tutor/config.py, tutor/env.py
Plugin template paths of init jobs could not be found because they were searched for in the Tutor template root only.
=> fix: init template paths

requirements/base.in
An issue was reported here: https://app.slack.com/client/T02SNA1T6/CGE253B7V
CompletionItem was introduced in 8.0, so click needs to be upgraded when we `pip install tutor`.
=> fix: minimum click version is 8.0

changelog.d/20221124_161803_regis_HEAD.md, tests/commands/test_plugins.py, tests/test_serialize.py, tutor/commands/config.py, tutor/commands/plugins.py, tutor/serialize.py
This introduces auto-completion of `plugins` and `config` arguments: `plugins enable/disable NAME`, `plugins install PATH`, `config save --set KEY=VAL`, `config save --unset KEY`, `config printvalue KEY`. 
Of course, this auto-completion will only work when it is enabled in the user shell: https://docs.tutor.overhang.io/install.html#shell-autocompletion
=> feat: better autocompletion of `plugins` and `config` commands

requirements/base.in
The following syntax is only supported in jinja2>=2.10:
{% set jwt_rsa_key | rsa_import_key %}{{ JWT_RSA_PRIVATE_KEY }}{% endset %}
Thus, we bump the minimal working version of jinja2 in the base requirements.
See discussion: https://discuss.openedx.org/t/error-while-tutor-local-quickstart/8796
=> fix: TemplateSyntaxError with old jinja2

changelog.d/20221129_083631_regis_sec_drag_n_drop.md, tutor/templates/build/openedx/Dockerfile
Vulnerability is fixed by upgrading the xblock from v2.3.5 to v3.0.0. See announcement:
https://discuss.openedx.org/t/upcoming-security-release-xblock-drag-and-drop-v2/8768
=> sec: fix XSS vulnerability in drag-n-drop v2 xblock

changelog.d/20221207_071139_maria.grimaldi_fix_problem_templates.md, tutor/templates/build/openedx/Dockerfile
This PR adds a patch that fixes a syntax error in the Circuit Schematic Builder problem template reported [here](https://github.com/openedx/build-test-release-wg/issues/209) during the olive testing plan.
Please, let me know if this is the right place to add this fix.
=> fix: update problem templates according newer python versions

tutor/commands/k8s.py, tutor/commands/local.py, tutor/commands/upgrade/__init__.py
There is nothing to do in the upgrade from nutmeg to olive, but it's not a reason to crash this command.
Close #756.
=> fix: `tutor local upgrade --from=nutmeg`

changelog.d/20221212_235220_regis_fix_parameters_to_generic.md, requirements/base.in
People running typing-extensions==3.10 faced this error for just any tutor command:
$ tutor version
...
File "/usr/local/bin/tutor", line 5, in <module>
from tutor.commands.cli import main
File "/usr/local/lib/python3.8/dist-packages/tutor/commands/cli.py", line 7, in <module>
from tutor import exceptions, fmt, hooks, utils
File "/usr/local/lib/python3.8/dist-packages/tutor/hooks/__init__.py", line 7, in <module>
from . import actions, contexts, filters, priorities
File "/usr/local/lib/python3.8/dist-packages/tutor/hooks/actions.py", line 18, in <module>
class ActionCallback(Contextualized, t.Generic[P]):
File "/usr/lib/python3.8/typing.py", line 261, in inner
return func(*args, **kwds)
File "/usr/lib/python3.8/typing.py", line 890, in __class_getitem__ …
=> fix: "TypeError: Parameters to Generic[...]" error

CHANGELOG.md
v15.0.0 changelog includes entries from v14.0.0 (!!!). I assume this is because we did not delete these entries from the nightly changelog during the v14 upgrade.
Close #761.
=> docs: fix v15.0.0 changelog

changelog.d/20221213_163837_regis_backfill_persistent_grades.md, tutor/commands/k8s.py, tutor/commands/upgrade/common.py, tutor/commands/upgrade/k8s.py, tutor/commands/upgrade/local.py
In Olive, persistent grades are now mandatory. This was already the case in Nutmeg, but it didn't mean that existing, non-persistent grades were migrated to be persistent. This introduces a job that is run whenever a user upgrades from Nutmeg. Alternatively, it can be run manually with:
tutor local upgrade --from=nutmeg
See relevant documentation: https://openedx.atlassian.net/wiki/spaces/AC/pages/755171487/Migrating+to+Persistent+Grading#The-Persistent-Grades-Backfill
See discussion: https://app.slack.com/client/T02SNA1T6/C049JQZFR5E/thread/C02SNA1U4-1670937183.881709
=> feat: backfill persistent grades during upgrade

changelog.d/20221213_131305_regis_no_quickstart.md, tutor/commands/dev.py, tutor/commands/k8s.py, tutor/commands/local.py
We meant to get rid of `quickstart` in Olive, but somehow we forgot to delete the command.
=> depr: get rid of `quickstart` command

changelog.d/20221213_083234_regis_dev.md, changelog.d/20221213_090356_regis_dev.md, changelog.d/20221213_102202_regis_dev.md, tutor/commands/dev.py, tutor/templates/apps/openedx/settings/lms/development.py, tutor/templates/build/openedx/Dockerfile
- Upgrade openedx dev dependencies
- Skip separate openedx-dev building in `tutor dev launch`.
- Fix authn login in development (see [this conversation](https://discuss.overhang.io/t/tutor-login-fail-in-new-version/3083))
=> olive fixes

changelog.d/20230110_130740_cmuniz_built_in_generic_types.md, docs/conf.py, tests/commands/base.py, tests/commands/test_compose.py, tests/hooks/test_filters.py, tests/test_plugins_v0.py, tutor/commands/cli.py, tutor/commands/compose.py, tutor/commands/config.py, tutor/commands/dev.py, tutor/commands/images.py, tutor/commands/jobs.py, tutor/commands/local.py, tutor/commands/plugins.py, tutor/config.py, tutor/env.py, tutor/hooks/actions.py, tutor/hooks/contexts.py, tutor/hooks/filters.py, tutor/hooks/priorities.py, tutor/plugins/__init__.py, tutor/serialize.py, tutor/types.py
Changes annotations from `typing` to use built-in generic types from `__future__.annotations`
Closes https://github.com/openedx/wg-developer-experience/issues/130
=> refactor: change annotations to use built-in generic types

changelog.d/20230106_163518_regis_fix_example_com_links.md, tutor/templates/apps/openedx/settings/partials/common_all.py
When a user registers, they receive a confirmation email. This email contained two links to "https://example.com/..." urls. This was caused by the fact that the default site, indicated by SITE_ID=1, was example.com. We resolve this issue by setting instead SITE_ID=2, which should point to the site with the LMS domain name.
This is a potentially breaking change for platforms that have manually set to 1 the id of the LMS site in the database. These platforms should now set SITE_ID=1 via a plugin.
Alternatives we have considered include modifying the id field of the LMS site in the database. Unfortunately such a change would have important consequences, as the site ID is used as a foreign key for other models.
Note that non-https sites still include https links in the registration emails. …
=> fix: 'example.com' links in registration emails

changelog.d/20230109_134927_regis_fix_tinymce_formatting.md, tutor/templates/build/openedx/Dockerfile
See: https://discuss.openedx.org/t/text-component-does-not-remove-text-with-link-or-insert-a-link-to-text/9029
=> fix: backport fix for html component editing in studio

changelog.d/20230117_165024_regis_cors_whitelist.md, tutor/templates/apps/openedx/settings/cms/production.py, tutor/templates/apps/openedx/settings/lms/production.py
The LMS and CMS were producing lots of logs similar to:
cms_1                        | 2023-01-17 15:30:11,359 INFO 7 [openedx.core.djangoapps.cors_csrf.helpers] [user 7] [ip 31.223.46.44] helpers.py:64 - Origin 'https://studio.demo.openedx.overhang.io' was not in `CORS_ORIGIN_WHITELIST`; full referer was 'https://studio.demo.openedx.overhang.io/learning/course/course-v1:edX+DemoX+Demo_Course/home' and requested host was 'studio.demo.openedx.overhang.io'; CORS_ORIGIN_ALLOW_ALL=False
These warnings are produced by openedx.core.djangoapps.cors_csrf.helpers. I don't think they indicate any problem, but they pollute the logs. They are resolved by adding the "http(s)://<lms/cms host>" to CORS_ORIGIN_WHITELIST in production, so we did just that.
=> fix: get rid of `CORS_ORIGIN_WHITELIST` from lms/cms logs

changelog.d/20230106_190620_regis_hooks_api.md
* Remove redundant changelog line
* The change should NOT affect most developers ;)
=> docs: fix typos in hooks changelog entry

changelog.d/20230209_092607_regis_sec_lti.md, tutor/templates/build/openedx/Dockerfile
See advisory:
https://github.com/openedx/xblock-lti-consumer/security/advisories/GHSA-7j9p-67mm-5g87 Discussion:
https://discuss.openedx.org/t/upcoming-security-release-xblock-lti-consumer/9165 Pull requests:
https://github.com/openedx/xblock-lti-consumer/pull/331 https://github.com/openedx/edx-platform/pull/31724
=> sec: fix LTI consumer xblock grading

docs/conf.py, requirements/base.txt, requirements/dev.txt, requirements/docs.txt, tests/commands/test_compose.py, tutor/commands/config.py, tutor/core/hooks/filters.py
Cryptography in particular needs to be upgraded to 39.0.1: https://github.com/overhangio/tutor/security/dependabot/7 https://github.com/overhangio/tutor/security/dependabot/8
=> chore: upgrade requirements

changelog.d/20230214_105510_keith_fix_jobs_merge.md, tutor/commands/k8s.py, tutor/serialize.py
When a job is invoked, we now replace the job in k8s/jobs.yml instead of rewriting jobs.yml to only contain the relevant job. This allows patchStrategicMerge to work for jobs.
Fixes #791.
```
pip install --upgrade tutor-forum tutor-mfe git+https://gitlab.com/opencraft/dev/tutor-contrib-grove@keith/tutor-override-test
tutor plugins enable forum grove mfe
tutor config save
tutor k8s launch
```
`tutor k8s launch` will fail without these changes.
=> fix: patchStrategicMerge now works for kind:Job

tests/commands/test_plugins.py, tests/test_utils.py, tutor/commands/plugins.py, tutor/utils.py
This PR moves the format_table function to utils to reuse it.
When I try to reuse from plugins, for example, for PR #798, I have this error:
=> refactor: move format_table function to utils

changelog.d/20230307_132140_maria.grimaldi_fix_transcripts.md, tutor/templates/build/openedx/Dockerfile
This PR adds the following fix: https://github.com/openedx/wg-build-test-release/issues/247. This cherry-pick can be removed after olive.3 since a backport was already merged.
=> fix: use supported YouTube API for transcripts imports

changelog.d/20230310_045537_moises.gonzalez_fix_k8s_uwsgi_workers.md, tutor/templates/k8s/deployments.yml
The amount of workers processes that uWSGI spawns can be configured through the environment variable `UWSGI_WORKERS` which in turn can be adjusted with the `OPENEDX_LMS_UWSGI_WORKERS` and `OPENEDX_CMS_UWSGI_WORKERS` variables.
This env variable was missing from the k8s deployments.
=> fix: add the missing `UWSGI_WORKERS` env variable to the k8s deployments

docs/troubleshooting.rst
On some OS, high ulimit causes some container to use a lot of memory. We do not attempt to resolve this issue in Tutor because this is a mysql/uwsgi issue. Instead, we explain how to resolve it in the troubleshooting docs.
Close #671.
=> docs: troubleshoot high memory usage

changelog.d/20230313_163654_kdmc_dev_image_for_dev_do.md, tutor/templates/dev/docker-compose.jobs.yml
The lms-job and cms-job services were configured to use {{ DOCKER_IMAGE_OPENEDX }} rather than {{ DOCKER_IMAGE_OPENEDX_DEV }}.
This means that when running jobs in dev mode, a la:
tutor dev do init
a production image would be used, to the user's surprise.
FYI @bmtcril
Replace tutor/templates/jobs/init/lms.sh with:
```
echo '****************************'
pip freeze | grep debug-toolbar
echo '****************************'
```
Run `tutor config save` and `tutor dev do init -l lms`.
Without the fix, you would see no output between the asterisks.
With the fix, you should see `django-debug-toolbar==...`, because the dev image contains the django-debug-toolbar package.
* https://github.com/openedx/wg-developer-experience/issues/165
=> fix: use dev image for `tutor dev do`, not prod image

docs/configuration.rst
Credit to @bmtcril for pointing this out.
=> docs: clarify that extra pip requirements are a list, not a string

changelog.d/20230310_021412_moises.gonzalez_configurable_uwsgi.md, docs/reference/patches.rst, tutor/templates/apps/openedx/uwsgi.ini, tutor/templates/build/openedx/Dockerfile, tutor/templates/build/openedx/settings/uwsgi.ini, tutor/templates/k8s/deployments.yml, tutor/templates/kustomization.yml, tutor/templates/local/docker-compose.yml
The current invocation of uwsgi doesn't allow to modify any configuration value besides the amount of workers.
This changes introduces a new patch `uwsgi-config` and a `uwsgi.ini` file to be mounted on the container. This allows us to add additional configuration values or override the existing ones.
I've tested it by manually creating a cookie with a size big enough to exceed the maximum buffer size of 8192. This caused a crash when accessing the base lms page. Afterwards I added a small plugin:
```yaml
name: uwsgi
version: 0.1.0
patches:
uwsgi-config: |
buffer-size = 16384
```
And was able to access the page again. I duplicated the cookie a few times and was able to crash it again and the LMS logs reported the increased buffer size:
```
invalid request block size: 20564 (max …
```
=> feat: configure uwsgi through an ini file

changelog.d/20230313_110919_kdmc_mounted_init.md, docs/dev.rst, tutor/commands/jobs.py, tutor/templates/build/openedx/Dockerfile, tutor/templates/dev/docker-compose.jobs.yml, tutor/templates/jobs/init/mounted-edx-platform.sh
This is the part of [effort to make it easier to work with mounted repositories](https://github.com/openedx/wg-developer-experience/issues/146).
@regisb , previously we had agreed that it'd be good to [generate the .egg-info folder automatically using an init task](https://github.com/openedx/wg-developer-experience/issues/152#issuecomment-1379465966). I realized the other day, though, that we may as well do the same thing for installing node_modules and regenerating static assets too! With this change, **we can setup a dev env with a bind-mounted edx-platform in one command**.
In the future, I am still interesting in removing the need to reinstall node_modules and regenerate static assets; for now, though, I think that this is an improvement, and its user interface is compatible with the …
=> feat: full edx-platform setup with `tutor dev launch -m ...`

changelog.d/20230316_094112_regis_better_highlight_enabled_plugins.md, tutor/commands/plugins.py
In the output of `plugins list` it's difficult to see which plugins are enabled at a glance. This change adds a more visible checkmark to the output.
Ex:
$ tutor plugins list
NAME            STATUS          VERSION
cairn           ✅ enabled      15.0.3
discovery       installed       15.0.0
ecommerce       installed       15.0.1
forum           installed       14.0.0
mfe             ✅ enabled      15.0.5
minio           installed       15.1.0
=> feat: highlight enabled plugins with ✅

changelog.d/20230316_113639_regis_fix_yaml_patch_ordering.md, tests/test_plugins_v0.py, tutor/plugins/v0.py
v0 plugin patches were directly added to ENV_PATCH, while v1 patches were added to ENV_PATCHES. ENV_PATCHES items are forwarded to ENV_PATCH later at runtime, which means that yaml plugin patches were always loaded before v1 patches.
This was causing weird ordering issues, as discussed here: https://discuss.openedx.org/t/using-mfe-config-to-set-logo-trademark-url-for-the-footer-component-in-olive/9578
=> fix: v0 plugin patch ordering

docs/tutorials/arm64.rst
The ARM64 tutorial is a bit out of date. I have updated it to recommend MySQL 8 instead of MariaDB and remove the warnings about MariaDB, since MySQL 8 is officially supported by Open edX. Also, based on the discussion in https://github.com/open-craft/tutor-contrib-arm64/issues/1 and the new automated image builds for ARM64 in https://github.com/open-craft/tutor-contrib-arm64/pull/3 I have linked to the unofficial ARM64 plugin, for those who would like to use it.
=> docs: Update ARM64 tutorial

changelog.d/20230526_151849_johan.castiblanco_update_authsource_mongo.md, tutor/templates/apps/openedx/settings/partials/common_all.py
Update `authSource`  keyword argument to  `authsource`
Authsource was configurated in camelcase.
https://github.com/overhangio/tutor/blob/master/tutor/templates/apps/openedx/settings/partials/common_all.py#L16 Something I think is ok because pymongo uses it in camelcase. ![2023-04-03_10-52](https://user-images.githubusercontent.com/51926076/229563381-68a9430e-a3ec-42cd-bc8b-910f01be7f1e.png)
However, the error was presented because edx-platform use another variable when credentials are provided **(LOWERCASE)**. https://github.com/openedx/edx-platform/blob/master/xmodule/mongo_utils.py#L72
Looking more ,  the `auth_source `is configured with another key name:  `authsource` **(LOWERCASE)** from the kwargs. https://github.com/openedx/edx-platform/blob/master/xmodule/mongo_utils.py#L34
This …
=> fix: use correct case for authsource mongo

changelog.d/20230527_174319_codewithemad_kubeconfig.md, tutor/commands/k8s.py
in some cases, tutor might run inside a pod, which that pod has access to a cluster via role binding and a service account. this way, there's no ./kube/config file, but kubectl commands run with no issue.
Close #843
=> feat: Add support for loading in-cluster config when running inside a pod

changelog.d/20230613_091959_fghaas_mongodb_4_2_24.md, docs/configuration.rst, tutor/templates/config/defaults.yml
Bump the default image reference for MongoDB from 4.2.17 to 4.2.24, to address a critical issue present in versions 4.2.0 through 4.2.23.
References:
https://www.mongodb.com/docs/manual/release-notes/4.2/#patch-releases
https://jira.mongodb.org/browse/WT-10461
Fixes #854.
=> chore: Bump MongoDB default to version 4.2.24

changelog.d/20230620_163516_faraz.maqsood_faraz_add_temporary_patch_for_cache_program_command_issue_for_discovery.md, tutor/templates/build/openedx/Dockerfile
This PR is created as temporary fix for cache programs command that is used in tutor-discovery plugin to cache programs.
The issue link is [here](https://github.com/overhangio/tutor-discovery/issues/40).
=> fix: add a temporary patch for the fix of cache programs command error

changelog.d/20230622_123257_regis_k8s_fix_mysql8_start.md, tutor/templates/k8s/deployments.yml
The `--ignore-db-dir` option is no longer supported on MySQL 8. See: https://dev.mysql.com/doc/refman/8.0/en/upgrade-prerequisites.html
This option was causing the mysql container to fail.
=> fix: mysql deployment on k8s

docs/install.rst
@regisb 
[3 minutes ago](https://openedx.slack.com/archives/C049JQZFR5E/p1686164471558869?thread_ts=1686154946.792849&cid=C049JQZFR5E)
https://docs.tutor.overhang.io/install.html#upgrading I guess? Missing from these instructions are the usual "backup your stuff" and "read the changelog"...
=> docs: Tweak upgrade instructions

changelog.d/20230714_100627_kyle.md, tutor/commands/jobs.py
`tutor ... do settheme default` is meant to revert to the default theme.  However, in its current implementation, it creates SiteTheme objects pointing to a theme named "default", which doesn't exist, resulting in errors like:
Theme dirs:
[Path('/openedx/themes')]]
File "/openedx/edx-platform/openedx/core/djangoapps/theming/helpers.py", line 204, in get_current_theme
themes_base_dir=get_theme_base_dir(site_theme.theme_dir_name),
File "/openedx/edx-platform/openedx/core/djangoapps/theming/helpers.py", line 242, in get_theme_base_dir
raise ValueError(
ValueError: Theme 'default' not found in any of the following themes dirs,
This works from the perspective of the user, because a missing theme is treated as the default theme. However, the errors are …
=> fix: set default theme by simply deleting SiteTheme objects

tutor/templates/build/openedx/Dockerfile
scripts/copy-node-modules.sh replaces `openedx-assets npm`.
We run it automatically as a post-install NPM hook.
That means that the script must be available when running `npm clean-install`.
This should merge right after https://github.com/openedx/edx-platform/pull/32767 merges.
Part of: https://github.com/openedx/edx-platform/issues/31604
=> build: copy in copy-node-modules.sh for npm post-install hook

changelog.d/20230731_155418_regis_fix_discussion_units.md, tutor/templates/build/openedx/Dockerfile
This is a backport of a commit to the master branch: https://github.com/openedx/edx-platform/pull/32464
In particular, it will fix many issues that appear when the demo course is imported.
=> fix: ignore discussion units when forum is not enabled

changelog.d/20230623_170336_regis_http3.md, docs/tutorials/proxy.rst, tutor/templates/k8s/services.yml, tutor/templates/local/docker-compose.prod.yml
It was observed that waiting time was cut in half after http/3 was enabled. Plus, supporting http/3 is super easy :)
Close #845
=> feat: add support for http/3

changelog.d/20230731_110301_regis_fix_non_buildkit_build.md, tests/commands/test_images.py, tutor/commands/images.py, tutor/templates/build/openedx/Dockerfile
See comment here:
https://github.com/overhangio/tutor/pull/868#issuecomment-1640429396
See also the conversation that spawned this PR:
https://discuss.openedx.org/t/issue-in-tutor-palm-release-with-tuotr-dev-launch-while-installing/10629
=> fix: improve support of non-buildkit Docker build

changelog.d/20230816_184458_regis_fix_local_non_prod.md, tutor/commands/compose.py
User was no longer asked whether they wanted to run on prod or not. In other words, it was not convenient to run as local.overhang.io.
=> fix: ask whether we run as prod in `local launch`

CHANGELOG.md, tutor/templates/apps/openedx/settings/partials/common_cms.py
Exactly the same issue as https://github.com/overhangio/tutor/pull/649, but with Studio:
```python
*** Operational MODE: preforking ***
spawned uWSGI worker 1 (pid: 7, cores: 1)
spawned uWSGI worker 2 (pid: 9, cores: 1)
File "cms/wsgi.py", line 21, in <module>
import cms.startup as startup  # lint-amnesty, pylint: disable=wrong-import-position
File "/openedx/edx-platform/./cms/startup.py", line 10, in <module>
settings.INSTALLED_APPS  # pylint: disable=pointless-statement
File "/openedx/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
self._setup(name)
File "/openedx/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
self._wrapped = Settings(settings_module)
File …
```
=> fix: race condition could cause mkdirs() to fail with "file exists"

changelog.d/20230906_105044_regis_parse_pound_keys_in_settings.md, tests/test_serialize.py, tutor/serialize.py
Pound keys were interpreted as comments. This is annoying when we want to parse html color codes, such as in:
$ tutor config save --set "INDIGO_PRIMARY_COLOR=#225522"
$ tutor config printvalue INDIGO_PRIMARY_COLOR
null
Close #866.
=> fix: parse strings prefixed with "#" in `config save --set ...`

changelog.d/20231002_110754_regis_fix_ora2_uploads.md, tutor/templates/apps/openedx/settings/partials/common_lms.py
For some reason, the ora2 cache configuration had disappeared in the upgrade to Palm.
This issue was initially raised here:
https://discuss.openedx.org/t/palm-2-ora-file-upload-failure/11332
Close #907.
=> fix: file upload in open response assessments (ora2)

changelog.d/20231003_144841_paulo_mongodb_connect.md, tutor/templates/apps/openedx/settings/partials/common_all.py
This adds `connect=False` to the LMS and CMS' MongoDB connection configuration to prevent `ServerSelectionError` after a failover.
Related issue: https://github.com/overhangio/tutor/issues/865
=> fix: adds `connect=False` to MongoDB connection configuration

changelog.d/20231004_114528_dave_fix_cms_base_settings.md, tutor/templates/apps/openedx/settings/cms/development.py
The LMS was overriding CMS_BASE properly, but Studio (CMS) configuration was not. That meant that Studio's CMS_BASE in dev mode was using the devstack default of localhost:18010 (because this is what's defined in edx-platform). This in turn broke parts of Studio that use this value, such as the XBlock v2 API (/api/xblock/v2).
This commit derives the value of the CMS_BASE Django setting from Tutor's CMS_HOST config value, in the same way that the LMS does it.
=> fix: override CMS_BASE setting in Studio for dev

changelog.d/20231010_111112_regis_fix_py2neo.md, tutor/templates/build/openedx/Dockerfile
On Oct. 10, py2neo package was abruptly removed from pypi, GitHub, and the py2neo website now displays just a super funny meme: https://py2neo.org/
Yes, we should get rid of that dependency, but we are still supposed to support existing users. So we install py2neo from our fork.
=> fix: build error caused by removed py2neo package

changelog.d/20231011_005657_codewithemad_large_dev_image.md, tutor/templates/build/openedx/Dockerfile
This will fix large dev images caused by the large user ID ([this docker bug](https://github.com/moby/moby/issues/5419)).
Closes https://github.com/openedx/wg-developer-experience/issues/178
=> Fix: Large DEV Image

tutor/templates/apps/openedx/settings/partials/common_all.py
We are going to upgrade to Django 4.2 for Quince.
Issue: https://github.com/openedx/wg-build-test-release/issues/315
PR to edx-platform: https://github.com/openedx/edx-platform/pull/33516 (will be merged only after Tutor preparation for Django4.2)
Here I'm just updating to the new `50`/`51` DeprecationWarnings.
Also to be able to smoothly move from Django 3.2 to 4.2 I propose to add try/except block (for now).
=> chore: update deprecation warning for Django 4.2

changelog.d/20231106_202213_codewithemad.md, setup.py
We can use this to install tutor development packages inside ci jobs, with one line. it can be helpful for [this](https://github.com/overhangio/tutor-mfe/pull/155)
=> feat: dev added to extras_require

docs/troubleshooting.rst
It adds a note in the troubleshooting guide, offering solution for mitigating resource consumption issues related to BuildKit when building multiple images using Tutor.
=> docs: Update troubleshooting.rst with notes about docker buildkit

changelog.d/20231116_081945_i_rootless_docker.md, tests/test_utils.py, tutor/env.py, tutor/templates/dev/docker-compose.yml, tutor/utils.py
Unset `ulimits.memlock` for elasticsearch for Docker rootless devstacks.
Related issue:
- Fixes #876 
When running `tutor dev launch` in rootless docker, everything works except for elasticsearch. 
```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting rlimits for ready process: error setting rlimit type 8: operation not permitted: unknown
```
=> fix: fix `ulimits` error for elasticsearch in Docker rootless mode

changelog.d/20231120_160115_regis_nightly_common_version.md, docs/configuration.rst, tutor/config.py, tutor/templates/config/defaults.yml
Bumping the `OPENEDX_COMMON_VERSION` in the master branch usually creates a conflict when we merge the change in the nightly branch. To avoid this conflict, we add some logic to the `OPENEDX_COMMON_VERSION`.
This change should be invisible for most users.
This partially addresses issue #936.
=> feat: simplify nightly management

tutor/templates/jobs/init/cms.sh
This PR will enable the new-ish "copy & paste units" feature in Quince. Because it's a new feature and edx.org wants to roll it out later for their users, it's off by default in edx-platform. But Axim product is recommending it be on by default in Quince, because it's a useful, highly requested feature and there are no known issues with it. Operators can of course disable it easily via the django admin if for some reason they don't want it.
Most of the relevant code is already in Quince, but the features shown in the second "After" screenshot are waiting on a backport PR - https://github.com/openedx/edx-platform/pull/33866 . Whether or not that backport PR is merged, the flag enables new functionality and new UI on the course outline page.
=> feat: enable copy-paste of units by default

changelog.d/20231011_000434_codewithemad_save_configs.md, docs/plugins/intro.rst, docs/plugins/v0/gettingstarted.rst, docs/tutorials/plugin.rst, tests/test_utils.py, tutor/commands/plugins.py, tutor/config.py, tutor/plugins/__init__.py
This replaces https://github.com/overhangio/tutor/pull/917/
=> fix: save config and env on `plugins enable/disable`

changelog.d/20231205_113430_regis_local_edly_io.md, docs/dev.rst, docs/tutorials/theming.rst, tutor/interactive.py, tutor/templates/local/docker-compose.prod.yml
The new domain name points to 127.0.0.1, just like the previous one. We keep the local.overhang.io domain names for backward compatibility. In the future, we hope to migrate to "*.openedx.io" but that will not happen before Redwood.
Close #945
=> feat: local.overhang.io -> local.edly.io

changelog.d/20231009_164751_regis_mount_edx_platform_packages.md, docs/dev.rst, docs/reference/api/hooks/catalog.rst, docs/tutorials/edx-platform.rst, docs/tutorials/index.rst, tests/test_bindmount.py, tutor/bindmount.py, tutor/commands/compose.py, tutor/commands/images.py, tutor/hooks/catalog.py, tutor/plugins/__init__.py, tutor/plugins/openedx.py, tutor/templates/build/openedx/Dockerfile, tutor/templates/local/docker-compose.jobs.yml, tutor/templates/local/docker-compose.yml
These changes make to possible to run:
tutor mounts add /path/to/my-xblock
The xblock directory with then be auto-magically bind-mounted in the "openedx" image at build time, and the lms*/cms* containers at run time.
This makes it effectively possible to work as a developer on edx-platform requirements.
We take the opportunity to move some openedx-specific code to a dedicated module.
Close https://github.com/openedx/wg-developer-experience/issues/177
=> feat: auto-mount edx-platform python requirements

docs/tutorials/podman.rst
**Changes**
- Added note that `tutor local` expects a web proxy to be running in rootless mode for podman.
- Provided link to tutorial for how to run openedx behing a web proxy.
Fixes [this issue](https://github.com/overhangio/tutor/issues/959).
=> docs: add web proxy instructions for podman rootless mode

changelog.d/20231214_141533_alecar.main_survey_report_plugin.md, tutor/hooks/catalog.py, tutor/interactive.py
This PR creates a new hook Action that allows tutor plugins to interact with the configuration at the time of the interactive questionnaire that happens during `tutor local launch`.
None. The creation of the Action does not require anything from new or existing plugins. Current plugins that do not use this action will see absolutely no changes to the functionality of `tutor local launch`.
This Action was first needed when trying to create a plugin to send automatic and anonymized reports of usage.
For more context on that see:
- https://github.com/eduNEXT/tutor-contrib-surveyreport
- https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3872948238/Problem+Very+few+are+going+to+generate+and+send+the+Survey+Report.
A plugin using this Action to add a new question can be seen at: …
=> feat: add surveyreport questions

changelog.d/20231214_110904_regis_rsa_error.md, requirements/base.in
Running `tutor config save` with an outdated version of pycryptodome was failing with the following error:
Error: Missing configuration value: 'Crypto.PublicKey.RSA.RsaKey object' has no attribute 'dq'
This is because the "dq" attribute was only introduced in pycryptodome 3.17.0: https://www.pycryptodome.org/src/changelog#january-2023
To resolve this issue we bump the minimum requirements.
Close #962
=> fix: RsaKey.dq attribute error

.github/workflows/auto-add-to-project.yml
Adds a Github action to auto-add new PRs and issues to Overhang.io project https://github.com/orgs/overhangio/projects/4.
Requires a token with repo and project scopes in env variable ADD_TO_PROJECT_SECRET_TOKEN
- https://github.com/actions/add-to-project?tab=readme-ov-file#inputs
- https://stackoverflow.com/questions/62530078/github-auto-assign-issue-to-project
=> build: add Github action to auto-add new issues and PRs to project

changelog.d/20240118_155012_r.khetani.md, tutor/env.py
Short term solution to address issue raised in #975, which was causing tutor to throw exceptions when enabling theming plugins, which included file extensions not specified by `BIN_FILE_EXTENSIONS` in `env.py`
=> chore: Add .webp and .otf file extensions to list of binary file extensions

docs/plugins/examples.rst
Fixed extra indentation for the Google Analytics plugin example. The extra indentation makes the plugin fail when being activated.
=> Update examples.rst, fixed extra indentation

docs/tutor.rst
=> doc: update steps to release a new version

changelog.d/20240129_144929_kshitij_fix_tutor_docker_compose.md, tutor/templates/dev/docker-compose.yml
=> fix: Fix tutor when using docker compose 2.24.1

changelog.d/20240110_101228_kyle_importnewdemocourse.md, tests/commands/test_jobs.py, tutor/commands/jobs.py
This is a redo of https://github.com/overhangio/tutor/pull/976, with the following differences:
* Per @regisb's [suggestion](https://github.com/overhangio/tutor/pull/976#discussion_r1461952913), in `importdemocourse`, we now auto-find course.xml if `--repo-dir` is not provided. This simplifies the CLI and makes the command backwards-compatible 🎉
* Since the change is now compatible with any demo course version, I'm merging it to **master** instead of nightly. This means Tutor users can use it right away instead of waiting until Redwood.
* I changed importdemolibrary to **importdemolibraries**. Furthermore, instead of taking a `--repo-library-tar` argument, the command now searches for directories with library.xml files, run `tar` on them, and imports them. I've done this to:
1. Make its …
=> feat: enhance importdemocourse ; add importdemolibraries

changelog.d/20240208_111236_regis_infinite_course_cache.md, docs/reference/patches.rst, tutor/templates/apps/openedx/settings/partials/common_all.py, tutor/templates/apps/redis/redis.conf, tutor/templates/build/openedx/Dockerfile
See the discussion here: https://github.com/overhangio/tutor/pull/984
And the upstream PR here: https://github.com/openedx/edx-platform/pull/34210
The tl;dr is that the Redis course structure cache was growing without bounds. While the upstream fix should resolve that issue, we decided that Tutor should have a maxmemory limit and an eviction policy set for operational safety.
tutor local run cms ./manage.py cms shell -c "from django.core.cache import caches; c = caches['course_structure_cache']; [c.expire(key, 604800) for key in c.keys('*')]"
FYI @Ian2012 @ormsbee
=> fix: infinite cache growth

changelog.d/20240124_080753_i_plugins_xblocks.md, tutor/templates/build/openedx/Dockerfile
Pulls translations for plugins and XBlock using the newly introduced commands:
- https://github.com/openedx/edx-platform/pull/33698
- https://github.com/openedx/edx-platform/pull/33922
<details><summary>atlas pull results</summary>
```
$ docker run -it docker.io/overhangio/openedx:17.0.2-nightly bash
~/edx-platform$ git status
On branch master
Your branch is up to date with 'origin/master'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   cms/static/js/i18n/ar/djangojs.js
modified:   cms/static/js/i18n/az/djangojs.js
modified:   cms/static/js/i18n/bg-bg/djangojs.js
modified:   cms/static/js/i18n/ca/djangojs.js
modified:   cms/static/js/i18n/ca@valencia/djangojs.js …
```
=> feat: atlas pull for plugins and xblocks | FC-0012

changelog.d/20240315_163331_dawoud.sheraz_tutor_997.md, tutor/commands/jobs.py, tutor/templates/jobs/init/mounted-directories.sh
Fixes https://github.com/overhangio/tutor/issues/997
When xblocks and other installed packages are mounted, they are installed during image build. The dirs are copied over and then pip install takes place (resulting in egg-file generation). However, the dirs are not updated in host directories. When running tutor, the host files are re-mounted at run time. Due to missing egg-info, the installed packages no longer appear in pip list. This PR adds a small step during initialization that runs pip install on the mounted dirs if egg-info is missing.
- Checkout the branch & install.
- Clone scorm or any other xblock (as mentioned in https://github.com/overhangio/tutor/issues/997)
- mount the xblock
- Re-build open edx image. This might not be needed if you already have recent image build. In …
=> fix: ensure mounted installable packages are installed as expected

.github/workflows/test.yml, docs/conf.py
For #1006 
- Adds Python 3.12 checks in CI alongside 3.8
- Fix `make docs` in Python 3.12
`make docs` in Python 3.12 was failing for various reasons for variety of items (Action, Filter, FilterCallbackFunc). Mainly, the generic `type` does not get translated to `py:class` and is instead picked up as `py:data`. There were a few issues on Sphinx and some related items on Stackoverflow. Everyone handled it differently in some capacity. One suggestion was to ignore some of the type params but it did not result in docs building as expected (https://github.com/overhangio/tutor/pull/1008#issuecomment-1968906467). The appropriate fix for "Action & Filter" was to add entries in autodoc_type_aliases. FilterCallbackFunc was needed to be ignore because it does not translate to a py:class.
=> build: add python 3.12 checks alongside 3.8

requirements/plugins.txt
As `tutor-indigo` is enabled in `quince` by default but it is not installed when run `pip install tutor[full]`. `tutor plugins list` show this warning: `⚠️  Failed to enable plugin 'indigo': plugin 'indigo' is not installed.`
It is not installing `tutor-indigo`. I did fresh install of tutor by `pip install tutor[full]`
It installs `tutor-indigo` by default as other plugins are being installed.
=> Install tutor-indigo by default with tutor[full]

changelog.d/20240320_131420_dawoud.sheraz_redis_update.md, docs/configuration.rst, tutor/templates/config/defaults.yml
- Update redis to latest available version.
I updated the redis, pulled in latest images (when running launch), enabled discovery, and poked around a bit on Studio and Discovery. I did not see anything unusual in Redis logs. Only one error, some PID save, occurs at start of container. Though that error is also present for 7.2.1.
=> chore: update redis

changelog.d/20240409_175748_dawoud.sheraz_quince_3.md, tutor/templates/config/defaults.yml
Updating to open-release/quince.3, to be merged once tag is available after Tuesday, April 9, 4-5PM UTC
=> feat: update release to quince.3

changelog.d/20240410_102248_regis_node18.md, tutor/templates/build/openedx/Dockerfile
Without this fix, openedx Docker image building fails with the following error:
> [linux/arm64 nodejs-requirements 4/4] RUN
--mount=type=bind,from=edx-platform,source=/package.json,target=/openedx/edx-platform/package.json
--mount=type=bind,from=edx-platform,source=/package-lock.json,target=/openedx/edx-platform/package-lock.json
--mount=type=bind,from=edx-platform,source=/scripts/copy-node-modules.sh,target=/openedx/edx-platform/scripts/copy-node-modules.sh
--mount=type=cache,target=/root/.npm,sharing=shared     npm
clean-install --no-audit --registry=https://registry.npmjs.org/:
95.51 npm notice
95.51 npm notice New major version of npm available! 8.3.1 -> 10.5.1
95.51 npm notice Changelog:
<https://github.com/npm/cli/releases/tag/v10.5.1>
95.51 npm notice Run `npm install -g …
=> chore: upgrade to node 18 in edx-platform

changelog.d/20240410_102248_regis_node18.md, tutor/templates/build/openedx/Dockerfile
Reverts overhangio/tutor#1039, as the upstream Node upgrade was reverted: https://github.com/openedx/edx-platform/pull/34496
=> Revert "chore: upgrade to node 18 in edx-platform"

docs/troubleshooting.rst
**Issue**
- Git throws an EOF error while cloning large repositories on slow/unstable networks.
```
RUN mkdir -p /openedx/edx-platform &&     git clone https://github.com/openedx/edx-platform.git --branch open-release/quince.1 --depth 1 /openedx/edx-platform:
Cloning into '/openedx/edx-platform'...
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```
- This error is thrown while cloning `edx-platform` during the build process of the `openedx`/`openedx-dev` image.
https://github.com/overhangio/tutor/blob/13c420cb0a722b90bf7bb7984a3ee44eb150114d/tutor/templates/build/openedx/Dockerfile#L41-L43
**Changes**
- Added a troubleshooting guide for the issue thrown by git while cloning large repositories on slow/unstable networks.
- Since this issue is subjective …
=> docs: add git clone eof error troubleshooting

changelog.d/20240425_105236_braden_bind_mount_docs.md, docs/tutorials/edx-platform.rst, tutor/plugins/openedx.py
I couldn't get the edx-platform to persistently use my bind-mounted version of its dependency `openedx-learning`. I was about to write a giant post on Discourse to ask for help when I happened to notice that the documentation _does_ contain the answer I needed ("What if my edx-platform package is not automatically bind-mounted?"). The problem was, this key section was separated from the related section ("Working on edx-platform Python dependencies") by unrelated topics like how to run the unit tests.
So, this PR:
1) Moves that important section of the documentation up to where it's more relevant, and adds an explicit call out.
2) Also updates tutor to be able to auto-detect `openedx-learning` without a plugin - as it is becoming a key platform dependency and at least at OpenCraft, many …
=> Improve the "Working on edx-platform Python dependencies" documentation

changelog.d/20240329_164354_dawoud.sheraz_mongo_update.md, docs/configuration.rst, tutor/commands/upgrade/common.py, tutor/commands/upgrade/compose.py, tutor/commands/upgrade/k8s.py, tutor/templates/config/defaults.yml, tutor/templates/k8s/deployments.yml, tutor/templates/local/docker-compose.yml
Resolves https://github.com/overhangio/tutor/issues/1020
Because mongo is going from 4.4 --> 7, starting containers directly wouldn't work out of box. The container will keep on restarting with featureCompatibility error. Before running the containers, run `tutor <dev/local/k8s> upgrade --from=quince` to ensure Mongo is upgraded properly. See https://github.com/overhangio/tutor/issues/1020#issuecomment-2024794174 for more context for certain changes.
=> mongodb update

docs/tutorials/google-smtp.rst
Resolved #1025 
This pull request updates the documentation for setting up Google Mail as an SMTP server in Tutor. It replaces the deprecated "Less Secure Apps" access method with "Application-Specific Passwords" as recommended by Google for enhanced security.
Key Changes:
- Removed instructions related to enabling "Less Secure App Access," which Google has deprecated.
- Added detailed steps to set up "Application-Specific Passwords," including enabling 2-Step Verification and generating a secure 16-digit password.
- Included links to Google's official support page for creating app-specific passwords and a relevant discussion from the Open edX community forum that highlights issues related to SMTP setup.
=> docs: Update Google SMTP Setup to Use Application-Specific Passwords

changelog.d/20240502_200434_dawoud.sheraz_py311.md, tutor/templates/build/openedx/Dockerfile
Updates Tutor Open edX dockerfile to setup Python 3.11. Some dependencies have been updated as well.  Upsteam PR https://github.com/openedx/edx-platform/pull/34374. 
This PR is currently doing upgrade using pyenv. A followup PR that setups Python 3.11 from Python image would be merged later (https://github.com/overhangio/tutor/pull/1057). It is currently being tested. 
- Checkout the branch on your local
- Install your local tutor
- Ensure the tutor version is nightly. 
- Run `tutor config save`. Verify docker file has been updated
- Run `tutor images build opened --no-cache` to build a clean image. Verify the image builds as expected. Verify the PYthon inside image is 3.11
- Start tutor and verify LMS/CMS are running
=> feat: upgrade Open edX Image to Python 3.11

docs/faq.rst
* Remove outdated info on "native installation" which was deprecated in Juniper and pointed to an archived wiki page
* Updated language around Devstack being deprecated
* Added in pointer to Aspects
* "Open edX" should always be used as an adjective; fixed these mentions.
=> FAQ Update: Remove outdated info, update language

changelog.d/20240319_140241_andrew.bonnell_add_config_user_filter.md, tutor/config.py, tutor/hooks/catalog.py
[Context](https://discuss.openedx.org/t/tutor-config-unique-filter-not-overwriting-16-1-4/11712/2)
Implements a `CONFIG_USER` Filter that users can hook into and replace key values in their `config.yml` files
Similar in usage to the `CONFIG_UNIQUE` filter but it will always replace the value of a given key with the new value being passed in instead of skipping over it
Example usage in a tutor plugin, being used to fetch secrets from AWS Secrets Manager and put that dictionary of key:value pairs into config.yml to be ingested by tutor patches
```
@hooks.Filters.CONFIG_USER.add()
def fetch_secrets_from_aws(config):
secrets = s.do_config()
for secret in secrets:
config.append(
(secret, secrets[secret])
)
return config
```
=> Adds CONFIG_USER Filter

changelog.d/20240521_115552_dawoud.sheraz_security_patch.md, tutor/templates/build/openedx/Dockerfile
Part 1 for https://github.com/overhangio/tutor/issues/1067. 
Adds git patch for non-nightly mode for upstream security fix upstream  for "Privilege re-escalation in Studio after staff access removed"
- https://github.com/openedx/edx-platform/security/advisories/GHSA-99vw-2wrq-xh9x
- https://discuss.openedx.org/t/upcoming-security-fix-for-edx-platform-on-2024-05-17/13004
- https://github.com/openedx/edx-platform/commit/3ff69fd5813256f935f19c237ea0c42d4c16edbf
=> security: add upstream security patch in dockerfile

changelog.d/20240508_111948_abdul.muqadim_is_file_rendered_filter.md, tutor/env.py, tutor/hooks/catalog.py
**Description:**
This pull request introduces a new filter, IS_FILE_RENDERED, designed to enhance the flexibility of file handling within Tutor plugins. The new IS_FILE_RENDERED filter allows plugin developers to specify files that should not be rendered but instead copied .
**Implementation Details:**
The IS_FILE_RENDERED filter works by accepting a boolean flag and a file path. It returns a boolean indicating whether the file should be rendered. By default, all files are set to be rendered unless explicitly specified .
=> Add IS_FILE_RENDERED filter to enhance file processing flexibility

changelog.d/20240531_094930_kyle_assets_link.md, tutor/templates/build/openedx/Dockerfile
The --link flag is a feature of Docker BuildKit which tells Docker to treat the COPY'd layer independently of previous layers, enabling more aggressive build caching. For more details, see this Docker blog post [1].
When using COPY --link to copy files from a stage that does not contain /etc/passwd, we must --chown with $APP_USER_ID rather than app. Otherwise, the build would fail with "unknown user id".
[1] https://www.docker.com/blog/image-rebase-and-improved-remote-cache-support-in-new-buildkit/
(Originally, this change was part of my [ongoing big Dockerfile rework](https://github.com/kdmccormick/tutor/pull/34). I've pulled the `--link` change out into its own PR because I think it will be less controversial and easier to review.)
We have had reports from users that python/node …
=> perf: use COPY --link to increase Docker cache hit frequency

docs/troubleshooting.rst
I tried to remove as many "you" pronouns as possible. Also, clarify instructions on the "images build" resource issue.
=> docs: improvements to the "troubleshooting" page

requirements/plugins.txt
This is one of post-redwood release actions in nightly and updates plugins.txt to install plugins from their nightly branches instead of from PyPI.
=> chore: ensure plugins are installed from nightly branches in nightly

changelog.d/20240704_112127_danyal.faheem_fix_mysql_native_password_plugin.md, tutor/templates/k8s/deployments.yml, tutor/templates/local/docker-compose.yml
fixes #1089.
For tutor instances that were created with tutor 15 and earlier and then upgraded to tutor 18, the launch process would fail as the MySQL connection could not be made. 
This is because mysql-native-password was removed in MySQL 8.4.0. We turn it on temporarily to fix failing connections.
=> fix: add turn on mysql-native-password authentication plugin to fix broken connection for users upgrading from Tutor 15 or earlier

.github/workflows/release.yml
Update macos in release.yml to macos-12 as 11 has been deprecated https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
=> build: update macos runner for release.yml

docs/troubleshooting.rst
Add the troubleshooting links in the troubleshooting section documentation:
Follow-up PR: https://github.com/overhangio/tutor/pull/1019
=> chore: add docs link in troubleshooting section

changelog.d/20240725_221432_dawoud.sheraz_july_25_security_patch.md, tutor/templates/build/openedx/Dockerfile
Part 1 for https://discuss.openedx.org/t/security-upcoming-security-release-for-edx-platform-2024-07-25/13473, adds the commit patch in Dockerfile
upstream backport: https://github.com/openedx/edx-platform/pull/35180
=> security: add upstream security patch in Open edX image

tutor/templates/build/openedx/Dockerfile, tutor/templates/k8s/deployments.yml, tutor/templates/local/docker-compose.yml
Moves uwsgi file to openedx directory instead of edx-platform, resolves https://github.com/overhangio/tutor/issues/846. 
Both local and k8s are working on my system after this change (did a clean image build).
=> refactor: move uswgi out of platform directory

tutor/commands/compose.py
The warning message printed during `tutor local upgrade` was incorrectly indented.
I decided not to write a changelog entry, given how minor this change is.
=> fix: warning message indentation in upgrade

changelog.d/20240624_105125_kyle_test_mongo_host.md, docs/tutorials/edx-platform.rst, tutor/templates/build/openedx/Dockerfile
Currently, we are asking devs to set this env var manually before they run tests.
Why not just set it in the development image for them?
=> feat: set `EDXAPP_TEST_MONGO_HOST=mongodb` in openedx-dev

changelog.d/20240629_120748_codewithemad_cleanup_flag.md, docs/tutorials/edx-platform.rst, tests/commands/test_config.py, tests/test_config.py, tutor/commands/compose.py, tutor/commands/config.py, tutor/commands/k8s.py, tutor/commands/plugins.py, tutor/env.py, tutor/interactive.py
This will introduce `-c` `--clean` command, to make sure we have a new environment on save.
Close #967
=> feat: cleanup flag

changelog.d/20240816_141531_regis_patches_show.md, tests/commands/test_config.py, tutor/commands/config.py, tutor/plugins/__init__.py
I found myself in a situation where I wasn't sure if a patch was correctly added by the Indigo plugin. To troubleshoot that issue, I wanted to print that rendered patch. I thought it would make a nice addition to the CLI.
=> feat: add `patches show ...` command

docs/install.rst
This PR adds Running an older version of Open edX in the Installation section.
Context: Sometimes, we need another Open edX release different from the latest. So, by adding this documentation, we can guide what tutor version the person should install for different Open edX releases.
- Check the build test in the actions of this PR.
=> docs: add tutor compatibility notes

requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/docs.txt
The [latest commit](https://github.com/overhangio/tutor/commit/0f2229b181c584c760442be6f063ea77f120a41e) to nighly is breaking deployments because it's using the [packaging](https://github.com/overhangio/tutor/blob/master/tutor/commands/upgrade/common.py) package, which is not included in the requirements.
This PR adds that as a requirement.
Private Ref : [BB-9216](https://tasks.opencraft.com/browse/BB-9216)
=> chore: add missing requirement

changelog.d/20241001_123236_regis_celery.md, tutor/commands/compose.py, tutor/commands/local.py, tutor/templates/dev/docker-compose.yml, tutor/templates/local/docker-compose.prod.yml, tutor/templates/local/docker-compose.yml
In development, edx-platform runs with CELERY_ALWAYS_EAGER=True, which
means that lms-worker and cms-worker never catch celery tasks!
This change was heavily inspired by: https://github.com/overhangio/tutor/pull/1041
=> feat: do not run celery workers in development

docs/configuration.rst, docs/dev.rst, docs/k8s.rst, docs/troubleshooting.rst
This will fix a couple of typos and an issue with a URL, and remove trailing whitespace from a piece of code.
=> chore: fixed typos

changelog.d/20241010_131903_regis_local_openedx_io.md, docs/dev.rst, docs/tutorials/theming.rst, tutor/interactive.py, tutor/templates/local/docker-compose.prod.yml
This makes it more clear for everyone that Tutor is an Open edX distribution.
Close #1120
After this PR is merged, I'll push the corresponding changes to all plugins. It's mostly the READMEs that will be affected.
=> feat: migrate from *.local.edly.io to *.local.openedx.io

docs/k8s.rst
A section will be added to the Kubernetes documentation, explaining the apply command and the benefits of running a dry run before the final deployment.
#1138
=> docs: k8s dry run section added

changelog.d/20241023_155157_codewithemad_long_domain.md, tutor/templates/build/openedx/bin/site-configuration
Before this, building organizations with longer URLs failed since the name field inside Site model has a max_length=50
Close #1144
=> fix: site name limited to 50 characters

.github/workflows/release.yml, Makefile, changelog.d/20241010_122752_dawoud.sheraz_ubuntu_upgrade.md, tutor/templates/build/openedx/Dockerfile
Upgrade Open edX image to use Ubuntu ~~24.04~~ 22.04 (See https://github.com/overhangio/tutor/issues/1114#issuecomment-2429082353 for context on 24.04 -> 22.04 switch).
=> feat: update ubuntu

changelog.d/20241018_122745_danyal.faheem_run_mysql_8_1_as_separate_container.md, tutor/commands/upgrade/compose.py, tutor/commands/upgrade/k8s.py
This PR is a fix for the issues brought forward in #1102.
We do this because MySQL 8.1 does not have the `--mysql-native-password` option and when upgrading from tutor v15 -> v18, this container would crash as the option does not exist.
We have this option turned on for backwards compatibility from tutor v18.1.1 onwards as users who have upgraded all the way from MySQL v5.7 -> v8.4 have their original users created using the mysql_native_password authentication plugin. See #1090 for more details.
After this PR is merged in nightly, we should make a backport to master as well coupled with the changes already made in #1102.
=> fix: run MySQL 8.1 as a separate container during upgrade from Olive to Redwood

README.rst
This will fix the old YouTube URL returning 404.
=> fix: wrong YouTube URL

changelog.d/20240726_202449_danyal.faheem_mysql_upgrade_5_7_to_8_4.md, changelog.d/20241018_122745_danyal.faheem_run_mysql_8_1_as_separate_container.md, tutor/commands/upgrade/common.py, tutor/commands/upgrade/compose.py, tutor/commands/upgrade/k8s.py
Backport PR to master for #1102 and #1140. 
See #1090 for more details on the issue.
=> fix: upgrade MySQL from 5.7 to 8.1 first and then to 8.4

changelog.d/20241031_144431_regis_no_delete_env.md, tests/test_config.py, tutor/commands/compose.py, tutor/commands/config.py, tutor/commands/k8s.py, tutor/env.py, tutor/interactive.py
The introduction of the `-c/--clean` option caused the deletion prompt to be displayed for every call to `tutor config save --interactive`. This is not the desired behaviour, as decided here: https://github.com/overhangio/tutor/pull/1086#discussion_r1681744804
With this change, the prompt is only displayed when running: `tutor config save --interactive --clean`. The environment is still deleted on `tutor config save --clean`, but without prompt.
We refactored the code with hooks, which simplifies the signature of the interactive prompt function.
FYI @CodeWithEmad @kdmccormick
=> feat: don't prompt for env deletion on `tutor config save -i`

changelog.d/20241113_131448_feanil_fix_uwsgi_xml_issues_master.md, tutor/templates/build/openedx/Dockerfile
When uwsgi runs with xml support, it throws the following error on startup with the latest version of edx-platform:
```
xmlsec.InternalError: (-1, 'lxml & xmlsec libxml2 library version mismatch')
```
See https://github.com/xmlsec/python-xmlsec/issues/320 for more details on this.
Essentially, the uWSGI wheel is built against a different version of libxml2 and it causes this version mismach error when trying to load xmlsec.  The xml support in uWSGI is only needed for runing with xml configuration files, which tutor does not do.  Following the guidance of the above issue, I updated the `openedx` Dockerfile to no longer compile with any xml support as a part of the build. The time to build uWSGI was only slightly more than building from cache so I'm not concerned about major slowdowns in …
=> fix: Don't build uwsgi with xml support.

changelog.d/20241119_111602_fghaas_image_manifest.md, tutor/commands/images.py
Without this change, when building images with `--cache-to-registry`, BuildKit uses a proprietary cache artifact format, which breaks when using third-party registries such as [Harbor](https://goharbor.io/) or [ECR](https://aws.amazon.com/ecr/).
By adding the `image-manifest=true` option, BuildKit uses an OCI-compliant cache artifact format that should be compatible with all registries. This option requires BuildKit 0.12 or later (check with `docker buildx ls`).
See https://github.com/goharbor/harbor/issues/18941 and https://github.com/moby/buildkit/issues/2251 for background information.
Co-authored-by: @angonz
=> fix: When pushing images to registry cache, use image-manifest=true

changelog.d/20241119_100430_crisgarta8_celery_queues.md, tutor/hooks/catalog.py, tutor/plugins/openedx.py, tutor/templates/k8s/deployments.yml, tutor/templates/local/docker-compose.prod.yml
This PR implements two new similar filters to define the command for the celery workers.
=> feat: add a filter to define celery workers command

changelog.d/20241121_110954_regis_remove_docker_rootless.md, tests/test_utils.py, tutor/env.py, tutor/utils.py
This filter was used only by Elasticsearch, so we no longer need to include it in Tutor.
=> feat: get rid of `is_docker_rootless` template filter

requirements/plugins.txt, tutor/__about__.py
This PR contains the https://github.com/overhangio/tutor/pull/1153, plus two Nightly-specific (aka Main-specific) commits:
* **Change version suffix from nightly to main.** As indicated in the linked PR's changelog entry, this is a breaking change, as it will rename the default TUTOR_ROOT and TUTOR_PLUGINS_ROOT.
* **Load plugins from main branches rather than nightly branches**. This is a safe changes as long as the plugins have already renamed their branches. If they haven't, then pop this commit off and merge it in later.
=> Change version suffix to 'main' and load plugins from their main branches

tutor/plugins/openedx.py
After the announcement of tutor branch rename, [Braden mentioned](https://discuss.openedx.org/t/tutor-branches-rename/14455/2?u=syed_muhammad_dawoud) the environment migration for nightly did not work. Upon closer inspection, it seems the action was running on release and not main. When running on release, it was not checking the correct destination path and failing to rename. In case of release, the root would be `<path_to_project>/tutor'`. On main/nightly, it would ``<path_to_project>/tutor-nightly` which is what we want to rename to ``<path_to_project>/tutor-main`
=> fix: update nightly migration action

changelog.d/20241203_212810_danyal.faheem_fix_cms_worker_parameters.md, tutor/templates/local/docker-compose.prod.yml
This fixes a bug introduced in #1134 where opening a course would throw a 500 error because the Course Outline could not be found. This is because the cms-worker was being run with the lms-worker parameters and would never pick up the Course Outline Generation tasks.
=> fix: use cms celery parameters for cms-worker

changelog.d/20241114_115534_arunmozhi_add_config_edit_command.md, tutor/commands/config.py
Quickly launch the default YAML editor for editing the `config.yml` file.
As a developer working with multiple projects, I am constantly changing the tutor config and re-running the `tutor dev launch` to update the devstack. While it is as simple as running `vim $(tutor config printroot)/config.yml`, I often found myself wanting to simply express this better using tutor config edit. So this is an attempt at cross-platform solution doing the same. It might not be the best solution, but something to start with if someone else finds this useful and improves their DevEx.
*Caveat:* I have only tested this on Linux (both open and `xdg-open` works in mine, so it could be said Unix).
=> feat: adds `tutor config edit`

tutor/templates/jobs/init/cms.sh
Now that https://github.com/openedx/edx-platform/pull/35981 has merged to Sumac, solving https://github.com/openedx/modular-learning/issues/235 , we can update the command that Tutor uses to populate the initial Studio search index.
What this means:
* Brand new instances will get a working index, and be able to start using the features right away. The `init` during instance setup will be nearly-instant.
* Upgraded instances with a small amount of content will see a notice during `init` that they need to run `reindex_studio` manually. The index will be created automatically during `init`, but it will be incomplete (existing content absent, but new content will show up in it). The `init` during instance setup will be nearly-instant, and the reindex command will take a few minutes when run …
=> feat: avoid slow reindex of studio content during init

changelog.d/20241205_211837_danyal.faheem_add_dev_attach_command.md, docs/tutorials/edx-platform.rst, tutor/commands/compose.py
Edx-platform developers regularly utilize debuggers inside their codebase and the `tutor dev start` command does not allow attaching to containers on certain OSes such as MacOS. This command will allow users to attach a single running container using the `docker compose attach` command.
Caveats:
- Can only attach one service in one running terminal
=> fix: attach container stdin on tutor dev start <service>

changelog.d/20241107_164816_kyle_tutor_version_parts.md, tutor/env.py, tutor/hooks/catalog.py
=> feat: expose integer Tutor version parts to templates

changelog.d/20250102_143119_danyal.faheem_fix_meilisearch_init_job.md, tutor/templates/local/docker-compose.jobs.yml
Running the Meilisearch init job when the platform is stopped would crash as the meilisearch container wouldn't be running and the endpoint could not be hit.
We add a dependency in the lms-job on meilisearch as the meilisearch init job is run inside the lms container.
=> fix: add meilisearch as a dependency on lms-job

Makefile, changelog.d/20250108_094231_regis_sumac_warnings.md, tests/commands/test_images.py, tests/test_utils.py, tutor/commands/jobs.py, tutor/commands/jobs_utils.py, tutor/plugins/openedx.py, tutor/templates/apps/openedx/settings/partials/common_all.py, tutor/utils.py
This warning was popping up with every manage.py command. E.g:
$ ./manage.py lms shell -c "print(1)"
2025-01-08 08:33:37,921 WARNING 33 [py.warnings] [user None] [ip None] warnings.py:110 - /openedx/venv/lib/python3.11/site-packages/pgpy/constants.py:5: DeprecationWarning: 'imghdr' is deprecated and slated for removal in Python 3.13                                                                                                                                       import imghdr
With this change, we explicitely ignore this warning. We also get rid
of warning removal which no longer makes sense in Sumac and Django 4.
We also fix pylint checking and remove a couple of irrelevant TODO items.
=> feat: disable obnoxious "imghdr" warning in edx-platform

changelog.d/20250109_184104_regis_plugin_unload.md, tutor/plugins/v1.py
If we enable, then disable, then enable a plugin again within the same call to Tutor, then the plugin module is not imported properly the second time. This is because it remains in the import cache. We discovered this while implementing a long-running web app for Tutor.
=> fix: plugin enable/disable/enable

changelog.d/20250127_183638_danyal.faheem_support_other_databases_through_plugin.md, tutor/templates/apps/openedx/config/partials/auth.yml
The `openedx-auth` patch is placed in an inconvenient position where adding DATABASES, XQUEUE or EMAIL settings to the patch does not actually apply these settings as they are below the patch so they are always overriden by the settings defined in Tutor.
We move the patch to the bottom of the file so that these settings can be overriden by the patch.
=> fix: move openedx-auth patch to bottom of file to allow patching EMAIL and DATABASES settings

changelog.d/20250203_192055_danyal.faheem_allow_installing_scorm_xblock_using_patch.md, tutor/templates/build/openedx/Dockerfile
The openedx-scorm-xblock was inconveniently being installed right after this patch was defined.
This meant that the only way to install a custom scorm-xblock was to use the OPENEDX_EXTRA_PIP_REQUIREMENTS setting which is not as convenient as the patch itself.
=> fix: allow installing custom openedx-scorm-xblock using the `openedx-dockerfile-post-python-requirements` patch

changelog.d/20240718_171945_danyal.faheem_mysql_authentication_plugin_change.md, docs/local.rst, docs/troubleshooting.rst, tests/commands/test_jobs.py, tutor/commands/jobs.py, tutor/commands/jobs_utils.py
closes #1095
This PR is a continuation of the issue mentioned in #1089. 
- Add a do command to update the authentication plugin of MySQL users from mysql_native_password to caching_sha2_password.
- The command requires a username and password to function. The password can be provided as a CLI option with the `--password` option or interactively. The command can also be run non-interactively with the `--non-interactive` option as it might prompt for some confirmations otherwise. 
The commands necessary to update a native installation of tutor would be:
```
tutor local do update-mysql-authentication-plugin $(tutor config printvalue OPENEDX_MYSQL_USERNAME) --password=$(tutor config printvalue OPENEDX_MYSQL_PASSWORD) --non-interactive
tutor local do update-mysql-authentication-plugin $(tutor …
```
=> feat: add `do` command to update the authentication plugin of MySQL users

changelog.d/20250212_220952_dawoud.sheraz_sumac_2.md, docs/configuration.rst, tutor/templates/config/defaults.yml
Update Open edX Docker image tag to open-release/sumac.2 now that sumac.2 tag is out https://discuss.openedx.org/t/sumac-2-has-been-tagged/14992
=> feat: update to sumac.2 tag

docs/tutorials/theming.rst
The documentation for the `Themes` page contains an outdated theme name, `edx.org`. This PR updates it to the correct theme name, `red-theme`, which aligns with the theme present in the `edx-platform/theming` folder in the latest release.
=> Docs: Replace outdated theme name with correct theme name on themes docs page

docs/configuration.rst
It was noted in https://discuss.openedx.org/t/open-edx-indigo-greek-translations-po-and-json-not-applied-in-lms-mfe-tutor-19-0-2/15125/6 that these instructions were missing from the docs.
=> docs: Add commands for updating custom translations

changelog.d/20250324_115822_dawoud.sheraz_fix_dev_jobs_environment.md, tutor/templates/dev/docker-compose.jobs.yml
@ormsbee identified in  https://github.com/openedx/edx-platform/issues/36170#issuecomment-2744282360, as part of identifying core issue raised in https://github.com/overhangio/tutor/pull/1108#issuecomment-2744287105, that dev do jobs are not using dev settings and are using prod settings. Upon inspection, the bug is caused by the job yml not defining the DJANGO_SETTINGS_MODULE as part of environment. It is being done in local and k8s but missed in dev.
=> fix: update dev jobs to use correct Django settings

docs/faq.rst, docs/local.rst, docs/quickstart.rst, docs/tutorials/plugin.rst
With the move to docs.openedx.org, update outdated reference links.
Ref: openedx/docs.openedx.org#988
=> Update edx.rtd.io links to docs.openedx.org

changelog.d/20250417_162221_mlabeeb03_trigger_compose_started.md, tutor/commands/compose.py, tutor/commands/dev.py, tutor/commands/local.py, tutor/hooks/catalog.py, tutor/utils.py
closes #1193
This PR fixes the issue mentioned in #1193.
We have: 
- Added run to the list of commands that will stop the previously running platform. i.e. stop `dev` on `local run` and vice versa.
- Make it so the `stop` is executed only once even if multiple `run` commands are executed in the same tutor runtime.
- Check for the status or previously running platform using `docker compose ls`. This saves us from calling the `stop` command even when the platform was already stopped.
=> Trigger COMPOSE_PROJECT_STARTED on `run` command

tutor/templates/jobs/init/cms.sh
- Remove the need to enable the flag contentstore.enable_copy_paste_units in the CMS init script since this flag is always enabled. This change took place in redwood: https://github.com/openedx/edx-platform/pull/34742/files
=> chore: remove deprecated toggle

changelog.d/20250423_154820_muhammad.labeeb_show_exited_containers.md, tests/commands/test_dev.py, tutor/commands/compose.py, tutor/commands/dev.py
closes #1204 
This PR fixes the issue mentioned in #1204 which is the lack of information for running MFEs.
Added new command `tutor dev hosts` that displays the status of all MFE hosts in the dev environment.
=> feat: add new command `tutor dev hosts` to display status of MFEs

changelog.d/20250416_123930_nlevesq_docker_compose_prod_override.md, docs/local.rst, tutor/commands/local.py
This adds support for an optional `docker-compose.prod.override.yml` file used for `tutor local` commands. I'm proposing this because the current documentation suggests you can use `docker-compose.override.yml` to override services defined in `docker-compose.prod.yml`, but in practice this always errors.
Any `tutor dev` commands will try to use it and fail. Additionally even trying to run `tutor local start` (really anything that invokes `docker compose [start|up|restart]`) causes the equivalent of `tutor dev dc stop` to run, which will fail as services like `caddy` aren't defined for that project.
This example if put in `docker-compose.override.yml` will fail (under both `tutor dev` and `tutor local`), but if put in `docker-compose.prod.override.yml` both commands will work as expected: …
=> feat: add docker-compose.prod.override.yml support

docs/install.rst
This PR updates the installation documentation (install.rst) to recommend using a Python virtual environment when installing Tutor. The update is based on recurring issues observed in the community, such as permission errors on fresh systems, and challenges in managing dependencies. These concerns were raised in [Tutor Issue #1198](https://github.com/overhangio/tutor/issues/1198) and discussed in the [Open edX Forum](https://discuss.openedx.org/t/fresh-ubuntu-install/14974), where users reported problems due to system-level Python installations.
Added a Virtual Environment (Recommended) section under the "Requirements"
=> fix: add venv instructions in docs for beginners

.github/workflows/release.yml
Github release is failing https://github.com/overhangio/tutor/actions/runs/15110643974/job/42469163148 due to some cache issue on setup python action. It is happening because the action is dependent on a deprecated cache action. Updating it to v5 fixes it https://github.com/actions/setup-python/issues/1085
=> build: update setup-python action to fix release issue

changelog.d/20250513_150323_regis_stop_on_start.md, tutor/commands/compose.py, tutor/commands/dev.py, tutor/commands/local.py, tutor/utils.py
When we run `local/dev start` we expect that any running `dev/local` project will be stopped. Previously, we were running `docker compose ls` twice, and for all running Compose projects on the server. We changed this behaviour:
1. By swapping the project name check and the check for running compose projects, we run `docker compose ls` just once: for dev in local mode, and vice versa.
2. By checking only Compose projects in the context of local/dev. That way we ignore any other non-tutor project.
=> feat: better stop on start

changelog.d/20250514_161945_muhammad.labeeb_only_filter_tutor_jobs_in_k8s.md, tutor/commands/k8s.py
closes #1206
This PR is an improvement that fixes the issue mentioned in #1206 
Now we are only filtering jobs that are managed by tutor. This allows running tutor jobs even if other non tutor jobs are running the same namespace.
=> feat: only wait for tutor managed jobs while running k8s

changelog.d/20250527_092311_regis_plugin_install_without_pip.md, tests/commands/test_plugins.py, tutor/commands/plugins.py
This change addresses two issues:
1. When running tutor as `.venv/bin/tutor ...`, we might not have the right `pip` in the PATH. To resolve this, we install plugins with `python -m pip install ...`.
2. When pip is not available, but `uv` is, we should be using the latter, not the former.
Close #1228.
=> fix: support `plugins install ...` without pip, or pip outside path

.github/workflows/release.yml, Makefile
Gitlab build uses bootstrap-dev to install dependencies during release pipeline. This fails for new/major releases as the plugin versions are not available on Pypi. This PR re-adds bootstrap-dev-plugins (removed in https://github.com/overhangio/tutor/commit/cd96a9f22f614fe05037141ee6fef16398d49568#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52) to keep dev and plugin installation separate
=> build: separate bootstrap-dev and bootstrap-dev-plugins to fix Gitlab builds

Makefile, README.rst, changelog.d/20250805_140709_abdul.muqadim_remove_webui_from_tutor_nightly.md, requirements/plugins.txt, tutor/plugins/v0.py
- remove webui plugin  as it is deprecated.
- check tutor-webui deprecation issue for more info: https://github.com/overhangio/tutor-webui/issues/28
=> depr: remove webui plugin as it is deprecated

docs/tutorials/main.rst
Update third-party service reference from Elasticsearch to Meilisearch in Tutor Main instructions
=> docs: remove Elasticsearch from docs

docs/tutor.rst
Hi all, reading the docs I noticed an error in code formatting due to a missing space:
This fixes that! 😄
=> docs: Fix spacing for code syntax rendering

tutor/plugins/openedx.py
Sometimes I need to work on repos like `openedx-events` or `opaque-keys`, and it's inconvenient to do so without Tutor knowing to automatically include those in all of the edx-platform images. This just adds them to the list of repos that are auto-detected as being used in the `edx-platform` images like LMS and CMS images.
With this change, users can just use e.g. `tutor mounts add openedx-events`
=> Add auto-mounts for openedx-events and opaque-keys

docs/reference/patches.rst
The leading slash in the path portion was causing the search to be blank.
=> fix: Correct the GitHub Search URL
