.gitignore
tutor/config.py

We were bit by this. Fortunately we had everything under revision control, so we didn't lose any work.

Make sure tutor asks for permission before a possibly destructive action

---

tutor/templates/apps/openedx/settings/cms/common.py
tutor/templates/apps/openedx/settings/cms/development.py
tutor/templates/apps/openedx/settings/cms/production.py
tutor/templates/apps/openedx/settings/lms/common.py
tutor/templates/apps/openedx/settings/lms/development.py
tutor/templates/apps/openedx/settings/lms/production.py

Use `execfile` to reduce duplication in the settings.

Refactor common parts in settings

---

docs/faq.rst

First / third person description mismatch.

Change typo in FAQ

---

docs/plugins.rst
tutor/templates/apps/openedx/config/cms.env.json
tutor/templates/apps/openedx/config/lms.env.json

Solution for #276.
I noticed that there was a missing plugin in docs, let me know that it was just missing or if it was remove for a particular cause.

Add the ability to customize CMS and LMS Features setting

---

docs/local.rst

I was looking for this information when I found it in discourse. 
Changes proposed in https://github.com/overhangio/tutor/issues/290

Add instructions for database dumps

---

docs/configuration.rst

I've added the word _directory_ to finish the sentence.
I've removed one extra space to close the formatted code for the command.

Finishing sentence.

---

docs/podman.rst

Reference:
https://discuss.overhang.io/t/tutor-with-podman-not-working/905/2

Add warning about docker-compose/podman-compose compatibility issues

---

CHANGELOG.md
tutor/templates/build/openedx/Dockerfile

Hi, 
I was having problems rebuilding the openedx image (`tutor images build openedx`), more specifically those errors:
```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/libpython2.7-minimal_2.7.12-1ubuntu0~16.04.12_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/python2.7-minimal_2.7.12-1ubuntu0~16.04.12_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/libpython2.7-stdlib_2.7.12-1ubuntu0~16.04.12_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/python2.7_2.7.12-1ubuntu0~16.04.12_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed …
```

add apt update to fix some cache issues in Dockerfile

---

CHANGELOG.md
tutor/templates/build/openedx/Dockerfile

See: https://discuss.openedx.org/t/security-patch-for-xss-fixes/4820

security: apply security patch 27394

---

CHANGELOG.md
tutor/templates/build/openedx/Dockerfile

Also, fix video unit completion in LMS.

security: upgrade Django to 2.2.23

---

docs/configuration.rst

- New Forum config section added in `Configuration and customisation`
- New config value `FORUM_MONGODB_DATABASE` added in docs referencing to https://github.com/overhangio/tutor/pull/453

docs: New config value FORUM_MONGODB_DATABASE added in docs

---

docs/k8s.rst

Previous links resulted in 404.
Close #479.
This is ready for review @overhangio/tutor-developers. Cc @0x29a who opened #479.

docs: fix links kubectl docs

---

requirements/base.txt
requirements/dev.txt
requirements/docs.txt

I just applied `make upgrade-requirements`. This chore needs to be performed
once in a while.

chore: upgrade requirements

---

CHANGELOG.md
tutor/bindmounts.py
tutor/commands/compose.py
tutor/commands/context.py
tutor/commands/dev.py
tutor/commands/local.py
tutor/jobs.py
tutor/templates/dev/docker-compose.jobs.yml

This makes the architecture of jobs less clunky. Also, it makes it possible to override job configuration in development.

Improve docker-compose jobs architecture

---

CHANGELOG.md
Makefile
bin/main.py
requirements/plugins.txt

For more information, checkout the plugin docs:
https://github.com/overhangio/tutor-richie

feat: add richie to bundled plugins

---

docs/configuration.rst
docs/tutorials.rst
docs/tutorials/scale.rst
tutor/commands/k8s.py

- Add a `tutor k8s scale lms 11` command
- Create a "Running Open edX at scale" tutorial

feat: `k8s scale` command + tutorial

---

Makefile

sed on Mac doesn't seem to understand \n.
While I was in here, I fixed some typos.

build: 'make help' works nicer on Mac

---

docs/tutorials/google-smtp.rst

docs: fixed typo

---

tests/test_utils.py
tutor/commands/local.py
tutor/utils.py

test_utils tests were failing on macOS when the settings file was properly
defined and present.
Close #560.

fix: utils tests on macOS

---

tutor/templates/build/openedx/Dockerfile
tutor/templates/build/permissions/Dockerfile

see https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

use LABEL instead of MAINTAINER

---

docs/install.rst

docs: clarify container pruning during uninstallation

---

docs/install.rst

I'm not sure if you've seen my comments in https://github.com/overhangio/tutor/pull/574, anyway, here's the PR

docs: fix typo in uninstallation process

---

requirements/base.txt
tutor/plugins.py

As a consequence, we need to resolve a typing issue.

chore: upgrade mypy

---

docs/k8s.rst

This problem emerged here: https://discuss.overhang.io/t/discovery-user-creation-in-kubernetes-deployment/2442

docs: clarify how to run commands in k8s containers

---

CHANGELOG.md
Makefile
docs/k8s.rst
tutor/commands/compose.py
tutor/commands/k8s.py
tutor/utils.py

This is convenient to check for k8s template validity.

Add `k8s apply` command

---

docs/plugins/api.rst
docs/plugins/gettingstarted.rst
docs/reference.rst

Some tweaks I developed as I worked through the docs for the first time to build my first plugin. See my commit messages for more details.
Supersedes https://github.com/overhangio/tutor/pull/564
api.rst intro:
_________________________
api.rst commands:
________________________
gettingstarted.rst YAML plugins:
________________________
gettingstarted.rst Python plugins:

 docs: suggestions for plugin API and CLI reference docs

---

CHANGELOG.md
tutor/templates/config/defaults.yml

fix: upgrade exim-relay SMTP image to make it work on arm64

---

CHANGELOG.md
tutor/templates/build/openedx/Dockerfile

solve the issue https://github.com/overhangio/tutor/issues/597

dockerfile patch added in the minimal section

---

docs/tutorials/arm64.rst

docs: clarify image building on arm64

---

CHANGELOG.md
tutor/commands/k8s.py
tutor/jobs.py

`kubectl_apply` was missing a "root" argument.
Close #611.

fix: "unexpected args" error on k8s

---

CHANGELOG.md
tutor/__about__.py
tutor/templates/build/openedx/Dockerfile

Apply security patch from edx-platform fork

fix: apply edx-platform security patch

---

CHANGELOG.md
tutor/__about__.py
tutor/commands/compose.py
tutor/commands/dev.py
tutor/commands/local.py
tutor/hooks/consts.py

Fixes a bug introduced by this fix: https://github.com/overhangio/tutor/commit/514e3fce22d6c564831605677c45ec1564d803fa
Also, adds attribution for my changes as mentioned in https://github.com/overhangio/tutor/pull/656#issuecomment-1114228241

fix: mounts were not being rendered in dev mode 

---

docs/dev.rst

fix: dead links

---

CHANGELOG.md
docs/local.rst
tutor/utils.py

`Docker Compose` v2 compatibility fix #641

---

docs/troubleshooting.rst

Adding docs to capture some common errors I've
been seeing in Slack. I've experienced these
myself as well.
Tagging @regisb  for review.
@brian-smith-tcril, since you hit this, do you mind reviewing as well?

docs: add troubleshootoing docs for mysql connectivity errors

---

tutor/commands/dev.py
tutor/commands/local.py

Follow-on from https://github.com/overhangio/tutor/commit/fe901ab9de707ff076a2294e3d1e974eeb40456c

docs: in quickstart's helptext, note that it's renamed to 'launch'

---

tutor/hooks/consts.py

Some filter declaration were duplicated. We resolve this issue by properly sorting all filter declarations by alphabetical order.

fix: de-duplicate filter names

---

docs/tutorials/podman.rst

The podman documentation was pretty out of date, so I updated it and added a section about fixing SELinux errors that might crop up.

docs: Updated the Podman documentation

---

changelog.d/20230103_165634_regis_plugin_indices.md
docs/plugins/intro.rst
docs/reference/index.rst
docs/reference/indexes.rst
tests/commands/test_plugins.py
tests/test_plugin_indexes.py
tests/test_utils.py
tutor/commands/local.py
tutor/commands/plugins.py
tutor/env.py
tutor/hooks/catalog.py
tutor/plugins/indexes.py
tutor/templates/config/base.yml
tutor/types.py
tutor/utils.py

We implement this TEP: https://discuss.openedx.org/t/tutor-enhancement-proposal-tep-plugin-indices/8182
With plugin indexes, tutor users can install and upgrade plugins directly from indexes:
tutor plugins install ecommerce
tutor plugins index add contrib
tutor plugins install codejail
tutor plugins upgrade all
This change has been long in the coming \o/

feat: plugin indexes

---

tutor/templates/local/docker-compose.jobs.yml

Based on:
https://github.com/overhangio/tutor/issues/642#issuecomment-1483970113

docs: explain why docker-compose.jobs.yml exists

---

docs/plugins/examples.rst

Updates the Google Analytics example per https://github.com/overhangio/tutor/issues/837

docs: Update Google Analytics example to GA4

---

changelog.d/20230616_113533_regis.md
tutor/commands/k8s.py

fix: load kube config from file

---

docs/tutorials/arm64.rst

Just updating this page in the docs now that Tutor 16 includes everything out of the box :)

docs: update ARM tutorial

---

README.rst
changelog.d/20230801_201804_codewithemad_remove_wizard.md
docs/faq.rst
docs/plugins/intro.rst
tutor/commands/plugins.py
tutor/plugins/indexes.py

Close https://github.com/overhangio/tutor/issues/882

Fix: Remove Wizard

---

changelog.d/20230905_155859_regis_fix_render_config_lists.md
tests/test_env.py
tutor/env.py

fix: render list config items

---

changelog.d/20230926_172753_codewithemad_config_loaded_action.md
tutor/commands/config.py
tutor/config.py
tutor/hooks/catalog.py

This will introduce a new Action to tutor: CONFIG_LOADED
close #557

CONFIG_LOADED Action

---

docs/configuration.rst
docs/dev.rst
docs/intro.rst
docs/tutorials/plugin.rst

This will add more clarification to the debugging section + fix some typos.
mentioned here: https://github.com/overhangio/tutor/issues/949

docs: debugging

---

docs/tutor.rst

Additional information added in contribution section of tutor.rst about contributing in plugins

docs: Update tutor.rst with additional information about contributing in plugins

---

changelog.d/20240122_093036_regis_jwt_security.md
tutor/templates/build/openedx/Dockerfile

See:
https://github.com/openedx/edx-platform/security/advisories/GHSA-qx8m-mqx3-j9fm https://github.com/openedx/edx-platform/pull/34047

security: fix JWT scopes in XBlock callbacks

---

requirements/base.txt
requirements/dev.txt
requirements/docs.txt

See:
https://github.com/overhangio/tutor/security/dependabot/32
https://github.com/overhangio/tutor/security/dependabot/29

fix: security issues with jinja2 and pycryptodome

---

docs/tutorials/edx-platform.rst

docs: fix typo in MOUNTED_DIRECTORIES guide

---

changelog.d/20240403_155328_r.khetani_improvement_patch_proxy_directive.md
docs/reference/patches.rst
tutor/templates/apps/caddy/Caddyfile

Add the ability to patch proxy config for Caddy

---

docs/_ext/tutordocs.py
requirements/base.txt
requirements/dev.txt
requirements/docs.txt
tutor/commands/jobs.py
tutor/env.py
tutor/hooks/__init__.py
tutor/hooks/catalog.py
tutor/plugins/__init__.py

Address several security issues raised by Dependabot.

chore: upgrade jinja2,black,requests,idna,cryptography

---

changelog.d/20240619_122432_illia_k8s_no_volumes_no_fail.md
tutor/commands/k8s.py

Close #1030
My solution seems dirty to me, so I'm very much open to suggestions on how to improve it.

fix: do not fail on start when there are no persistent volume claims

---

changelog.d/20240812_112508_dawoud.sheraz_redwood_2.md
docs/configuration.rst
tutor/templates/build/openedx/Dockerfile
tutor/templates/config/defaults.yml

Update OPENEDX_COMMON_VERSION to redwood.2 
https://discuss.openedx.org/t/redwood-2-has-been-tagged/13635

feat: update to redwood.2

---

requirements/base.txt
requirements/dev.txt
requirements/docs.txt

This is to address a few vulnerabilities in these libraries:
https://github.com/overhangio/tutor/security/dependabot/54 https://github.com/overhangio/tutor/security/dependabot/53 https://github.com/overhangio/tutor/security/dependabot/48 https://github.com/overhangio/tutor/security/dependabot/46 https://github.com/overhangio/tutor/security/dependabot/52 https://github.com/overhangio/tutor/security/dependabot/51 https://github.com/overhangio/tutor/security/dependabot/49 https://github.com/overhangio/tutor/security/dependabot/47 https://github.com/overhangio/tutor/security/dependabot/50

chore: upgrade zipp, urllib3, certifi reqs

---

requirements/dev.txt

See https://github.com/overhangio/tutor/security/dependabot/55

chore: upgrade cryptography package

---

README.rst

Nope, we are not on Twitter (or X). And the youtube channel was renamed.

docs: update social links

---

changelog.d/20241024_111339_dawoud.sheraz_redwood_3.md
docs/configuration.rst
tutor/templates/config/defaults.yml

- Upgrade Open edX Common version to redwood.3

feat: upgrade to redwood.3

---

requirements/plugins.txt
tutor/__about__.py

Update version_suffix and plugins.txt on main branch post sumac release

chore: add main version suffix, update plugins.txt to install main branches

---

changelog.d/20250312_120309_dawoud.sheraz_fix_hatch_build.md
pyproject.toml

Fix installation issue by adding hatch_build in sdist https://github.com/pypa/hatch/discussions/964#discussioncomment-6972973

build: Add hatch_build in sdist to fix installation issues

---

changelog.d/20250416_183637_mlabeeb03_add_deck.md
requirements/plugins.txt

Added https://github.com/overhangio/tutor-deck to the list of installed plugins.

feat: add deck

---

changelog.d/20250519_104625_dawoud.sheraz_sumac_3.md
docs/configuration.rst
tutor/templates/config/defaults.yml

open-release/sumac.3 tag has been released https://discuss.openedx.org/t/sumac-3-has-been-tagged/15950, updating tutor release to use sumac.3

feat: upgrade to sumac.3
